export const CARDS = [
  {"id":0,"tag":"sentences","en":"I went to a restaurant with a friend to eat Korean food","pin":"wǒ hé péng yǒu qù fàn guǎn chī hán guó cài","char":"我和朋友去饭馆吃韩国菜"},
  {"id":1,"tag":"sentences","en":"Who did you go with?","pin":"hé shéi qù？","char":"和谁去？"},
  {"id":2,"tag":"core","en":"come back / go back","pin":"huí lai / huí qù","char":"回来 / 回去"},
  {"id":3,"tag":"food","en":"dumplings (boiled)","pin":"shuǐ jiǎo","char":"水饺"},
  {"id":4,"tag":"core","en":"give","pin":"gěi","char":"给"},
  {"id":5,"tag":"sentences","en":"I will call my mum","pin":"wǒ huì gěi wǒ de mā ma dǎ diàn huà","char":"我会给我的妈妈打电话"},
  {"id":6,"tag":"sentences","en":"Will you call me?","pin":"nǐ huì gěi wǒ dǎ diàn huà","char":"你会给我打电话"},
  {"id":7,"tag":"core","en":"sit / take (transport)","pin":"zuò","char":"坐"},
  {"id":8,"tag":"core","en":"do (action)","pin":"zuò","char":"做"},
  {"id":9,"tag":"core","en":"work (noun)","pin":"gōng zuò","char":"工作"},
  {"id":10,"tag":"sentences","en":"What do you do?","pin":"nǐ zuò shén me？","char":"你做什么？"},
  {"id":11,"tag":"sentences","en":"What are you doing right now?","pin":"nǐ zài zuò shén me？","char":"你在做什么？"},
  {"id":12,"tag":"sentences","en":"What can you do?","pin":"nǐ huì zuò shén me？","char":"你会做什么？"},
  {"id":13,"tag":"sentences","en":"Apples are delicious","pin":"píng guǒ hěn hǎo chī","char":"苹果很好吃"},
  {"id":14,"tag":"core","en":"door","pin":"mén","char":"门"},
  {"id":15,"tag":"sentences","en":"What time does it open?","pin":"shén me shí hou kāi mén？","char":"什么时候开门？"},
  {"id":16,"tag":"sentences","en":"It opens at 8 o'clock","pin":"bā diǎn kāi mén","char":"八点开门"},
  {"id":17,"tag":"time","en":"what time?","pin":"jǐ diǎn","char":"几点"},
  {"id":18,"tag":"sentences","en":"I got on the bus","pin":"wǒ zuò shàng chē le","char":"我坐上车了"},
  {"id":19,"tag":"sentences","en":"I got off the bus","pin":"wǒ xià chē le","char":"我下车了"},
  {"id":20,"tag":"core","en":"down / get off","pin":"xià","char":"下"},
  {"id":21,"tag":"sentences","en":"I live in England","pin":"wǒ zhù zài yīng guó","char":"我住在英国"},
  {"id":22,"tag":"core","en":"how long?","pin":"duō jiǔ le","char":"多久了"},
  {"id":23,"tag":"sentences","en":"How long have you lived in England?","pin":"nǐ zhù zài yīng guó duō jiǔ le？","char":"你住在英国多久了？"},
  {"id":24,"tag":"sentences","en":"I have lived in England for six years","pin":"wǒ zhù zài yīng guó liù nián le","char":"我住在英国六年了"},
  {"id":25,"tag":"core","en":"to become","pin":"chéng wéi","char":"成为"},
  {"id":26,"tag":"core","en":"by / through","pin":"tōng guò","char":"通过"},
  {"id":27,"tag":"sentences","en":"I became a doctor through studying","pin":"wǒ tōng guò xué xí chéng wéi le yī shēng","char":"我通过学习成为了医生"},
  {"id":28,"tag":"sentences","en":"I went to work at the hospital","pin":"wǒ qù le yī yuàn gōng zuò","char":"我去了医院工作"},
  {"id":29,"tag":"core","en":"start a shift","pin":"shàng bān","char":"上班"},
  {"id":30,"tag":"sentences","en":"I finished my shift","pin":"wǒ xià bān le","char":"我下班了"},
  {"id":31,"tag":"sentences","en":"I finish work at 6pm","pin":"wǒ xià wǔ liù diǎn xià bān","char":"我下午六点下班"},
  {"id":32,"tag":"sentences","en":"It is raining today","pin":"jīn tiān xià yǔ","char":"今天下雨"},
  {"id":33,"tag":"sentences","en":"He is a teacher","pin":"tā shì lǎo shī","char":"他是老师"},
  {"id":34,"tag":"sentences","en":"I have a dictionary","pin":"wǒ yǒu yī běn zì diǎn","char":"我有一本字典"},
  {"id":35,"tag":"core","en":"this is me","pin":"zhè shì wǒ","char":"这是我"},
  {"id":36,"tag":"core","en":"I am here","pin":"wǒ zài zhèr","char":"我在这儿"},
  {"id":37,"tag":"sentences","en":"Where are you?","pin":"nǐ zài nǎ？","char":"你在哪？"},
  {"id":38,"tag":"sentences","en":"Who are you?","pin":"nǐ shì shéi？","char":"你是谁？"},
  {"id":39,"tag":"sentences","en":"What is this?","pin":"zhè shì shén me？","char":"这是什么？"},
  {"id":40,"tag":"objects","en":"cup","pin":"bēi zi","char":"杯子"},
  {"id":41,"tag":"money","en":"how much?","pin":"duō shǎo qián？","char":"多少钱？"},
  {"id":42,"tag":"money","en":"one yuan","pin":"yī kuài qián","char":"一块钱"},
  {"id":43,"tag":"numbers","en":"hundred","pin":"bǎi","char":"百"},
  {"id":44,"tag":"numbers","en":"thousand","pin":"qiān","char":"千"},
  {"id":45,"tag":"numbers","en":"ten thousand","pin":"wàn","char":"万"},
  {"id":46,"tag":"numbers","en":"100 million","pin":"yì","char":"亿"},
  {"id":47,"tag":"slang","en":"forever (1314)","pin":"yī shēng yí shì","char":"一生一世"},
  {"id":48,"tag":"slang","en":"I love you (520)","pin":"wǒ ài nǐ","char":"我爱你"},
  {"id":49,"tag":"sentences","en":"How old are you?","pin":"nǐ duō dà le？","char":"你多大了？"},
  {"id":50,"tag":"sentences","en":"How do you do this?","pin":"zhè zěn me zuò？","char":"这怎么做？"},
  {"id":51,"tag":"core","en":"and you?","pin":"nǐ ne？","char":"你呢？"},
  {"id":52,"tag":"core","en":"inside","pin":"lǐ","char":"里"},
  {"id":53,"tag":"core","en":"where","pin":"nǎ lǐ / nǎr","char":"哪里 / 哪儿"},
  {"id":54,"tag":"core","en":"when?","pin":"shén me shí hou？","char":"什么时候？"},
  {"id":55,"tag":"food","en":"wine / alcohol","pin":"jiǔ","char":"酒"},
  {"id":56,"tag":"phrases","en":"Happy Birthday","pin":"shēng rì kuài lè","char":"生日快乐"},
  {"id":57,"tag":"phrases","en":"Happy New Year","pin":"xīn nián kuài lè","char":"新年快乐"},
  {"id":58,"tag":"core","en":"happy","pin":"kuài lè","char":"快乐"},
  {"id":59,"tag":"food","en":"cake","pin":"dàn gāo","char":"蛋糕"},
  {"id":60,"tag":"phrases","en":"I don't know","pin":"wǒ bù zhī dào","char":"我不知道"},
  {"id":61,"tag":"core","en":"don't have / didn't","pin":"méi yǒu","char":"没有"},
  {"id":62,"tag":"core","en":"drink","pin":"hē","char":"喝"},
  {"id":63,"tag":"food","en":"coffee","pin":"kā fēi","char":"咖啡"},
  {"id":64,"tag":"core","en":"play / hit / call","pin":"dǎ","char":"打"},
  {"id":65,"tag":"core","en":"delicious","pin":"hěn hǎo chī","char":"很好吃"},
  {"id":66,"tag":"phrases","en":"great!","pin":"tài hǎo le","char":"太好了"},
  {"id":67,"tag":"core","en":"want","pin":"xiǎng yào","char":"想要"},
  {"id":68,"tag":"core","en":"things","pin":"dōng xi","char":"东西"},
  {"id":69,"tag":"core","en":"also","pin":"yě","char":"也"},
  {"id":70,"tag":"sentences","en":"I drank coffee","pin":"wǒ hē le kā fēi","char":"我喝了咖啡"},
  {"id":71,"tag":"phrases","en":"hello (on phone)","pin":"wéi","char":"喂"},
  {"id":72,"tag":"sentences","en":"I go home","pin":"wǒ huí jiā","char":"我回家"},
  {"id":73,"tag":"sentences","en":"Where is your home?","pin":"nǐ de jiā zài nǎ？","char":"你的家在哪？"},
  {"id":74,"tag":"core","en":"other people","pin":"bié rén","char":"别人"},
  {"id":75,"tag":"core","en":"hot","pin":"rè","char":"热"},
  {"id":76,"tag":"core","en":"cold (weather)","pin":"lěng","char":"冷"},
  {"id":77,"tag":"core","en":"cool (food/drink)","pin":"liáng","char":"凉"},
  {"id":78,"tag":"core","en":"ice","pin":"bīng","char":"冰"},
  {"id":79,"tag":"places","en":"train station","pin":"huǒ chē zhàn","char":"火车站"},
  {"id":80,"tag":"core","en":"outside","pin":"wài miàn","char":"外面"},
  {"id":81,"tag":"objects","en":"table","pin":"zhuō zi","char":"桌子"},
  {"id":82,"tag":"objects","en":"phone (mobile)","pin":"shǒu jī","char":"手机"},
  {"id":83,"tag":"objects","en":"computer","pin":"diàn nǎo","char":"电脑"},
  {"id":84,"tag":"sentences","en":"I am inside the house","pin":"wǒ zài jiā lǐ miàn","char":"我在家里面"},
  {"id":85,"tag":"time","en":"midnight – 5am","pin":"líng chén","char":"凌晨"},
  {"id":86,"tag":"time","en":"morning (5–9am)","pin":"zǎo shàng","char":"早上"},
  {"id":87,"tag":"time","en":"late morning (9am–12pm)","pin":"shàng wǔ","char":"上午"},
  {"id":88,"tag":"time","en":"noon","pin":"zhōng wǔ","char":"中午"},
  {"id":89,"tag":"time","en":"afternoon","pin":"xià wǔ","char":"下午"},
  {"id":90,"tag":"time","en":"evening","pin":"wǎn shàng","char":"晚上"},
  {"id":91,"tag":"time","en":"dusk","pin":"bàng wǎn","char":"傍晚"},
  {"id":92,"tag":"food","en":"breakfast","pin":"zǎo fàn","char":"早饭"},
  {"id":93,"tag":"food","en":"lunch","pin":"wǔ fàn","char":"午饭"},
  {"id":94,"tag":"food","en":"dinner","pin":"wǎn fàn","char":"晚饭"},
  {"id":95,"tag":"time","en":"this year","pin":"jīn nián","char":"今年"},
  {"id":96,"tag":"time","en":"next year","pin":"míng nián","char":"明年"},
  {"id":97,"tag":"time","en":"last year","pin":"qù nián","char":"去年"},
  {"id":98,"tag":"time","en":"this month","pin":"zhè ge yuè","char":"这个月"},
  {"id":99,"tag":"time","en":"next month","pin":"xià ge yuè","char":"下个月"},
  {"id":100,"tag":"time","en":"last month","pin":"shàng ge yuè","char":"上个月"},
  {"id":101,"tag":"time","en":"this week","pin":"zhè ge xīng qī","char":"这个星期"},
  {"id":102,"tag":"time","en":"Monday","pin":"xīng qī yī","char":"星期一"},
  {"id":103,"tag":"time","en":"Sunday","pin":"xīng qī tiān","char":"星期天"},
  {"id":104,"tag":"time","en":"weekend","pin":"zhōu mò","char":"周末"},
  {"id":105,"tag":"core","en":"half (time)","pin":"bàn","char":"半"},
  {"id":106,"tag":"sentences","en":"How many minutes do you need?","pin":"nǐ xū yào duō shǎo fēn zhōng？","char":"你需要多少分钟？"},
  {"id":107,"tag":"core","en":"before / previously","pin":"yǐ qián","char":"以前"},
  {"id":108,"tag":"core","en":"after / later","pin":"hòu","char":"后"},
  {"id":109,"tag":"sentences","en":"in 5 minutes","pin":"wǔ fēn zhōng hòu","char":"五分钟后"},
  {"id":110,"tag":"sentences","en":"What time is it now?","pin":"xiàn zài shì jǐ diǎn？","char":"现在是几点？"},
  {"id":111,"tag":"time","en":"one week ago","pin":"yì zhōu qián","char":"一周前"},
  {"id":112,"tag":"core","en":"already","pin":"yǐ jīng","char":"已经"},
  {"id":113,"tag":"clothing","en":"clothes","pin":"yī fu","char":"衣服"},
  {"id":114,"tag":"clothing","en":"red","pin":"hóng","char":"红"},
  {"id":115,"tag":"clothing","en":"T-shirt","pin":"T xù","char":"T恤"},
  {"id":116,"tag":"clothing","en":"short sleeve","pin":"duǎn xiù","char":"短袖"},
  {"id":117,"tag":"clothing","en":"long sleeve","pin":"cháng xiù","char":"长袖"},
  {"id":118,"tag":"clothing","en":"wear","pin":"chuān","char":"穿"},
  {"id":119,"tag":"places","en":"school","pin":"xué xiào","char":"学校"},
  {"id":120,"tag":"core","en":"some","pin":"yì xiē","char":"一些"},
  {"id":121,"tag":"core","en":"eat food","pin":"chī fàn","char":"吃饭"},
  {"id":122,"tag":"core","en":"or (in a question)","pin":"hái shì","char":"还是"},
  {"id":123,"tag":"objects","en":"plate","pin":"pán zi","char":"盘子"},
  {"id":124,"tag":"core","en":"ok / can / may","pin":"kě yǐ","char":"可以"},
  {"id":125,"tag":"core","en":"often","pin":"jīng cháng","char":"经常"},
  {"id":126,"tag":"sentences","en":"How is the weather today?","pin":"jīn tiān tiān qì zěn me yàng？","char":"今天天气怎么样？"},
  {"id":127,"tag":"music","en":"music","pin":"yīn yuè","char":"音乐"},
  {"id":128,"tag":"music","en":"song","pin":"gē","char":"歌"},
  {"id":129,"tag":"sentences","en":"I am listening to a song","pin":"wǒ zài tīng gē","char":"我在听歌"},
  {"id":130,"tag":"core","en":"sunset","pin":"rì luò","char":"日落"},
  {"id":131,"tag":"core","en":"right? (tag question)","pin":"ba","char":"吧"},
  {"id":132,"tag":"core","en":"name","pin":"míng zi","char":"名字"},
  {"id":133,"tag":"sentences","en":"What is your name?","pin":"nǐ jiào shén me míng zi？","char":"你叫什么名字？"},
  {"id":134,"tag":"core","en":"come here","pin":"guò lai","char":"过来"},
  {"id":135,"tag":"core","en":"times (occurrences)","pin":"cì","char":"次"},
  {"id":136,"tag":"sentences","en":"I like eating fruit","pin":"wǒ xǐ huān chī shuǐ guǒ","char":"我喜欢吃水果"},
  {"id":137,"tag":"phrases","en":"no need","pin":"bú yòng","char":"不用"},
  {"id":138,"tag":"phrases","en":"you're welcome","pin":"bié kè qi","char":"别客气"},
  {"id":139,"tag":"sentences","en":"next year I'll fly to China","pin":"míng nián wǒ zuò fēi jī qù zhōng guó","char":"明年我坐飞机去中国"},
  {"id":140,"tag":"core","en":"take a taxi","pin":"dǎ chē","char":"打车"},
  {"id":141,"tag":"core","en":"watch / look","pin":"kàn","char":"看"},
  {"id":142,"tag":"family","en":"grandpa (dad's side)","pin":"yé yé","char":"爷爷"},
  {"id":143,"tag":"family","en":"grandma (dad's side)","pin":"nǎi nai","char":"奶奶"},
  {"id":144,"tag":"family","en":"grandpa (mum's side)","pin":"lǎo yé","char":"老爷"},
  {"id":145,"tag":"family","en":"grandma (mum's side)","pin":"lǎo lao","char":"姥姥"},
  {"id":146,"tag":"core","en":"big / small","pin":"dà / xiǎo","char":"大 / 小"},
  {"id":147,"tag":"core","en":"a bit","pin":"yì diǎn","char":"一点"},
  {"id":148,"tag":"phrases","en":"let me think","pin":"ràng wǒ xiǎng xiang","char":"让我想想"},
  {"id":149,"tag":"phrases","en":"please speak more slowly","pin":"màn yì diǎn","char":"慢一点"},
  {"id":150,"tag":"phrases","en":"very pleased to meet you","pin":"hěn gāo xìng rèn shì nǐ","char":"很高兴认识你"},
  {"id":151,"tag":"core","en":"can / be able to","pin":"néng","char":"能"},
  {"id":152,"tag":"core","en":"all / everybody","pin":"dōu","char":"都"},
  {"id":153,"tag":"sentences","en":"today it's very cold","pin":"jīn tiān hěn lěng","char":"今天很冷"},
  {"id":154,"tag":"sentences","en":"too hot","pin":"tài rè le","char":"太热了"},
  {"id":155,"tag":"sentences","en":"every student","pin":"měi ge xué shēng","char":"每个学生"},
  {"id":156,"tag":"core","en":"every day","pin":"měi tiān","char":"每天"},
  {"id":157,"tag":"objects","en":"paper","pin":"zhǐ","char":"纸"},
  {"id":158,"tag":"sentences","en":"Can you give me a piece of paper?","pin":"nǐ kě yǐ gěi wǒ yì zhāng zhǐ ma？","char":"你可以给我一张纸吗？"},
  {"id":159,"tag":"sentences","en":"Please give me a glass of water","pin":"qǐng gěi wǒ yì bēi shuǐ","char":"请给我一杯水"},
  {"id":160,"tag":"core","en":"need","pin":"xū yào","char":"需要"},
  {"id":161,"tag":"sentences","en":"I am in front of you","pin":"wǒ zài nǐ qián miàn","char":"我在你前面"},
  {"id":162,"tag":"clothing","en":"shoes","pin":"xié","char":"鞋"},
  {"id":163,"tag":"music","en":"pop music","pin":"liú xíng yīn yuè","char":"流行音乐"},
  {"id":164,"tag":"food","en":"buy groceries","pin":"mǎi cài","char":"买菜"},
  {"id":165,"tag":"core","en":"brand","pin":"pái zi","char":"牌子"},
  {"id":166,"tag":"food","en":"iced tea","pin":"bīng chá","char":"冰茶"},
  {"id":167,"tag":"sentences","en":"Please give me a cup of cold water","pin":"qǐng gěi wǒ yī bēi liáng shuǐ","char":"请给我一杯凉水"},
  {"id":168,"tag":"sentences","en":"I took a taxi home","pin":"wǒ zuò chū zū chē huí jiā","char":"我坐出租车回家"},
  {"id":169,"tag":"sentences","en":"everyone goes to China","pin":"dà jiā dōu qù zhōng guó","char":"大家都去中国"},
  {"id":170,"tag":"sentences","en":"every day","pin":"měi tiān","char":"每天"},
  {"id":171,"tag":"sentences","en":"I am wearing a piece of clothing","pin":"wǒ chuān le yí jiàn yī fu","char":"我穿了一件衣服"},
  {"id":172,"tag":"sentences","en":"I can cook because I'm not working tomorrow","pin":"wǒ néng zuò fàn yīn wèi míng tiān wǒ bù qù gōng zuò","char":"我能做饭因为明天我不去工作"},
  {"id":173,"tag":"sentences","en":"large / medium / small cup","pin":"dà bēi / zhōng bēi / xiǎo bēi","char":"大杯 / 中杯 / 小杯"},
  {"id":174,"tag":"sentences","en":"What size do you want?","pin":"nǐ xiǎng yào shén me dà xiǎo de？","char":"你想要什么大小的？"},
  {"id":175,"tag":"phrases","en":"at a friend's house","pin":"zài péng yǒu de jiā","char":"在朋友的家"},
  {"id":176,"tag":"slang","en":"really? / for real? (lit. real or fake?)","pin":"zhēn de jiǎ de？","char":"真的假的？"},
  {"id":177,"tag":"slang","en":"for real? (short form)","pin":"zhēn jiǎ？","char":"真假？"},
  {"id":178,"tag":"sentences","en":"What are you doing right now? (emphatic)","pin":"nǐ zhèng zài zuò shén me？","char":"你正在做什么？"},
  {"id":179,"tag":"core","en":"-ing (right now) — progressive marker","pin":"zhèng zài","char":"正在"},
  {"id":180,"tag":"sentences","en":"I am studying Chinese (right now)","pin":"wǒ zhèng zài xué xí zhōng wén","char":"我正在学习中文"},
  {"id":181,"tag":"core","en":"Chinese person / Chinese people","pin":"zhōng guó rén","char":"中国人"},
  {"id":182,"tag":"slang","en":"what (colloquial = 什么)","pin":"shá","char":"啥"},
  {"id":183,"tag":"slang","en":"do (colloquial = 做)","pin":"gàn","char":"干"},
  {"id":184,"tag":"slang","en":"whatcha doing? (colloquial)","pin":"gàn shá ne？","char":"干啥呢？"},
  {"id":185,"tag":"sentences","en":"I have already eaten breakfast","pin":"wǒ yǐ jīng chī le zǎo fàn le","char":"我已经吃了早饭了"},
  {"id":186,"tag":"sentences","en":"I have already eaten breakfast (alt)","pin":"wǒ yǐ jīng chī zǎo fàn le","char":"我已经吃早饭了"},
  {"id":187,"tag":"places","en":"restaurant (3 synonyms)","pin":"fàn diàn / fàn guǎn / cān tīng","char":"饭店 / 饭馆 / 餐厅"},
  {"id":188,"tag":"sentences","en":"I'm going to the restaurant with my friend","pin":"wǒ hé wǒ de péng yǒu yì qǐ qù fàn guǎn","char":"我和我的朋友一起去饭馆"},
  {"id":189,"tag":"sentences","en":"When are you (plural) going?","pin":"nǐ men shén me shí hou qù？","char":"你们什么时候去？"},
  {"id":190,"tag":"sentences","en":"We're going to the restaurant at 6pm","pin":"wǒ men xià wǔ liù diǎn qù fàn guǎn","char":"我们下午六点去饭馆"},
  {"id":191,"tag":"phrases","en":"do (it) once more","pin":"zài zuò yí cì","char":"再做一次"},
  {"id":192,"tag":"phrases","en":"eat one more","pin":"zài chī yí ge","char":"再吃一个"},
  {"id":193,"tag":"phrases","en":"have another cup of coffee","pin":"zài hē yì bēi kā fēi","char":"再喝一杯咖啡"},
  {"id":194,"tag":"phrases","en":"one more time (lit. come once again)","pin":"zài lái yí cì","char":"再来一次"},
  {"id":195,"tag":"phrases","en":"sorry — it's nothing / no worries","pin":"duì bù qǐ — méi shì","char":"对不起 — 没事"},
  {"id":196,"tag":"numbers","en":"nine","pin":"jiǔ","char":"九"},
  {"id":197,"tag":"core","en":"long time","pin":"jiǔ","char":"久"},
  {"id":198,"tag":"sentences","en":"if you're hungry, just eat","pin":"nǐ è le jiù chī","char":"你饿了就吃"},
  {"id":199,"tag":"sentences","en":"if you want it, buy it (corrected: jiù not jiǔ)","pin":"nǐ yào jiù mǎi","char":"你要就买"},
  {"id":200,"tag":"sentences","en":"I'm going to the shop to buy apples and Chinese food","pin":"wǒ qù shāng diàn mǎi píng guǒ hé zhōng guó cài","char":"我去商店买苹果和中国菜"},
  {"id":201,"tag":"sentences","en":"Who are you going with?","pin":"nǐ hé shéi yì qǐ qù？","char":"你和谁一起去？"},
  {"id":202,"tag":"sentences","en":"I go to a Chinese restaurant because I like Chinese food","pin":"wǒ qù zhōng fàn guǎn，yīn wèi wǒ xǐ huān chī zhōng guó cài","char":"我去中饭馆，因为我喜欢吃中国菜"},
  {"id":203,"tag":"food","en":"spicy hotpot","pin":"là de huǒ guō","char":"辣的火锅"},
  {"id":204,"tag":"core","en":"then / so / that","pin":"nà","char":"那"},
  {"id":205,"tag":"core","en":"so / therefore","pin":"suǒ yǐ","char":"所以"},
  {"id":206,"tag":"core","en":"computer science","pin":"jì suàn jī kē xué","char":"计算机科学"},
  {"id":207,"tag":"places","en":"Western restaurant","pin":"xī cān tīng","char":"西餐厅"},
  {"id":208,"tag":"core","en":"when / at the time when (…的时候)","pin":"de shí hou","char":"的时候"},
  {"id":209,"tag":"core","en":"but","pin":"dàn shì","char":"但是"},
  {"id":210,"tag":"food","en":"spicy","pin":"là","char":"辣"},
  {"id":211,"tag":"core","en":"now","pin":"xiàn zài","char":"现在"},
  {"id":212,"tag":"places","en":"America / USA","pin":"měi guó","char":"美国"},
  {"id":213,"tag":"core","en":"from … to …","pin":"cóng … dào …","char":"从…到…"},
  {"id":214,"tag":"phrases","en":"for me / in my opinion","pin":"duì wǒ lái shuō","char":"对我来说"},
  {"id":215,"tag":"core","en":"left","pin":"zuǒ","char":"左"},
  {"id":216,"tag":"core","en":"right","pin":"yòu","char":"右"},
  {"id":217,"tag":"phrases","en":"go straight ahead","pin":"xiàng qián zǒu","char":"向前走"},
  {"id":218,"tag":"core","en":"to leave","pin":"lí kāi","char":"离开"},
  {"id":219,"tag":"core","en":"good-looking","pin":"hǎo kàn","char":"好看"},
  {"id":220,"tag":"core","en":"female / girl","pin":"nǚ","char":"女"},
  {"id":221,"tag":"core","en":"why","pin":"wèi shén me","char":"为什么"},
  {"id":222,"tag":"numbers","en":"two (+ measure word)","pin":"liǎng","char":"两"},
  {"id":223,"tag":"places","en":"supermarket","pin":"chāo shì","char":"超市"},
  {"id":224,"tag":"places","en":"shopping mall","pin":"shāng chǎng","char":"商场"},
  {"id":225,"tag":"time","en":"week","pin":"zhōu","char":"周"},
  {"id":226,"tag":"food","en":"noodles","pin":"miàn","char":"面"},
  {"id":227,"tag":"phrases","en":"you're welcome (no need to thank)","pin":"bú yòng xiè","char":"不用谢"},
  {"id":228,"tag":"core","en":"to speak / talk","pin":"shuō huà","char":"说话"},
  {"id":229,"tag":"core","en":"recently","pin":"zuì jìn","char":"最近"},
  {"id":230,"tag":"core","en":"busy","pin":"máng","char":"忙"},
  {"id":231,"tag":"core","en":"please / to invite","pin":"qǐng","char":"请"},
  {"id":232,"tag":"phrases","en":"excuse me (may I ask)","pin":"qǐng wèn","char":"请问"},
  {"id":233,"tag":"core","en":"to get up","pin":"qǐ chuáng","char":"起床"},
  {"id":234,"tag":"core","en":"to like","pin":"xǐ huān","char":"喜欢"},
  {"id":235,"tag":"objects","en":"book","pin":"shū","char":"书"},
  {"id":236,"tag":"core","en":"English (language)","pin":"yīng wén","char":"英文"},
  {"id":237,"tag":"core","en":"Chinese (language)","pin":"zhōng wén","char":"中文"},
  {"id":238,"tag":"core","en":"to meet / see","pin":"jiàn","char":"见"},
  {"id":239,"tag":"phrases","en":"see a doctor","pin":"kàn yī shēng","char":"看医生"},
  {"id":240,"tag":"core","en":"to listen","pin":"tīng","char":"听"},
  {"id":241,"tag":"core","en":"must / should / have to","pin":"děi","char":"得"},
  {"id":242,"tag":"core","en":"to speak / say","pin":"shuō","char":"说"},
  {"id":243,"tag":"core","en":"to read (aloud)","pin":"dú","char":"读"},
  {"id":244,"tag":"core","en":"to write","pin":"xiě","char":"写"},
  {"id":245,"tag":"core","en":"Chinese characters","pin":"hàn zì","char":"汉字"},
  {"id":246,"tag":"core","en":"to see","pin":"kàn jiàn","char":"看见"},
  {"id":247,"tag":"family","en":"dad","pin":"bà ba","char":"爸爸"},
  {"id":248,"tag":"core","en":"dog","pin":"gǒu","char":"狗"},
  {"id":249,"tag":"core","en":"cat","pin":"māo","char":"猫"},
  {"id":250,"tag":"core","en":"often","pin":"cháng cháng","char":"常常"},
  {"id":251,"tag":"core","en":"to drive","pin":"kāi chē","char":"开车"},
  {"id":252,"tag":"objects","en":"chair","pin":"yǐ zi","char":"椅子"},
  {"id":253,"tag":"core","en":"to sleep","pin":"shuì jiào","char":"睡觉"},
  {"id":254,"tag":"places","en":"Korea","pin":"hán guó","char":"韩国"},
  {"id":255,"tag":"core","en":"Korean (language)","pin":"hán wén","char":"韩文"},
  {"id":256,"tag":"core","en":"hungry","pin":"è","char":"饿"},
  {"id":257,"tag":"food","en":"distilled liquor (shochu / soju)","pin":"shāo jiǔ","char":"烧酒"},
  {"id":258,"tag":"sentences","en":"What time do you go to work? — I start work at 8am","pin":"jǐ diǎn qù gōng zuò？— zǎo shang bā diǎn qù shàng bān","char":"几点去工作？— 早上八点去上班"},
  {"id":259,"tag":"sentences","en":"I met many Chinese students","pin":"wǒ jiàn dào hěn duō zhōng guó xué shēng","char":"我见到很多中国学生"},
  {"id":260,"tag":"sentences","en":"I studied medicine, so I became a doctor","pin":"wǒ xué yī，suǒ yǐ wǒ chéng wéi le yī shēng","char":"我学医，所以我成为了医生"},
  {"id":261,"tag":"sentences","en":"How long have you been a doctor?","pin":"nǐ chéng wéi yī shēng duō jiǔ le？","char":"你成为医生多久了？"},
  {"id":262,"tag":"sentences","en":"(it's been) ten years","pin":"shí nián le","char":"十年了"},
  {"id":263,"tag":"sentences","en":"I like Chinese food, but it's too spicy","pin":"wǒ xǐ huān zhōng guó cài，dàn shì tài là le","char":"我喜欢中国菜，但是太辣了"},
  {"id":264,"tag":"sentences","en":"I go from England to America","pin":"wǒ cóng yīng guó dào měi guó","char":"我从英国到美国"},
  {"id":265,"tag":"sentences","en":"I will leave work at 6pm","pin":"wǒ xià wǔ liù diǎn huì lí kāi gōng zuò","char":"我下午六点会离开工作"},
  {"id":266,"tag":"sentences","en":"this person is good-looking","pin":"zhè ge rén hěn hǎo kàn","char":"这个人很好看"},
  {"id":267,"tag":"sentences","en":"Have you eaten?","pin":"nǐ chī le ma？","char":"你吃了吗？"},
  {"id":268,"tag":"sentences","en":"How have you been recently?","pin":"zuì jìn guò de zěn me yàng？","char":"最近过得怎么样？"},
  {"id":269,"tag":"sentences","en":"Have you eaten breakfast?","pin":"chī zǎo fàn le ma？","char":"吃早饭了吗？"},
  {"id":270,"tag":"sentences","en":"Excuse me, I'd like two coffees, is that ok?","pin":"qǐng wèn，wǒ xiǎng yào liǎng bēi kā fēi，kě yǐ ma？","char":"请问，我想要两杯咖啡，可以吗？"},
  {"id":271,"tag":"sentences","en":"Excuse me, can you give me two coffees?","pin":"qǐng wèn，nǐ kě yǐ gěi wǒ liǎng bēi kā fēi ma？","char":"请问，你可以给我两杯咖啡吗？"},
  {"id":272,"tag":"sentences","en":"I have two cups","pin":"wǒ yǒu liǎng ge bēi zi","char":"我有两个杯子"},
  {"id":273,"tag":"sentences","en":"I have two cups of coffee","pin":"wǒ yǒu liǎng bēi kā fēi","char":"我有两杯咖啡"},
  {"id":274,"tag":"sentences","en":"Do you get up and read English books? — I read Chinese books","pin":"nǐ qǐ chuáng kàn yīng wén shū ma？— wǒ kàn zhōng wén shū","char":"你起床看英文书吗？— 我看中文书"},
  {"id":275,"tag":"sentences","en":"I listen to the teacher speak","pin":"wǒ tīng lǎo shī shuō huà","char":"我听老师说话"},
  {"id":276,"tag":"sentences","en":"You should listen to the teacher","pin":"nǐ děi tīng lǎo shī shuō huà","char":"你得听老师说话"},
  {"id":277,"tag":"sentences","en":"I speak English","pin":"wǒ shuō yīng wén","char":"我说英文"},
  {"id":278,"tag":"phrases","en":"please read (aloud)","pin":"qǐng dú yí xià","char":"请读一下"},
  {"id":279,"tag":"sentences","en":"I don't know how to write Chinese characters","pin":"wǒ bù zhī dào zěn me xiě hàn zì","char":"我不知道怎么写汉字"},
  {"id":280,"tag":"sentences","en":"I can't write Chinese characters","pin":"wǒ bú huì xiě hàn zì","char":"我不会写汉字"},
  {"id":281,"tag":"sentences","en":"Last year I saw my dad","pin":"qù nián wǒ kàn jiàn le wǒ de bà ba","char":"去年我看见了我的爸爸"},
  {"id":282,"tag":"sentences","en":"I often go to the supermarket to buy fruit","pin":"wǒ cháng cháng qù chāo shì mǎi shuǐ guǒ","char":"我常常去超市买水果"},
  {"id":283,"tag":"sentences","en":"What shall we do?","pin":"wǒ men zuò shén me？","char":"我们做什么？"},
  {"id":284,"tag":"sentences","en":"I slept well","pin":"wǒ shuì de hěn hǎo","char":"我睡得很好"},
  {"id":285,"tag":"sentences","en":"I am working (right now)","pin":"wǒ zhèng zài gōng zuò","char":"我正在工作"},
  {"id":286,"tag":"sentences","en":"I'm hungry right now","pin":"wǒ zhèng è zhe","char":"我正饿着"},
  {"id":287,"tag":"core","en":"to run / jog","pin":"pǎo bù","char":"跑步"},
  {"id":288,"tag":"core","en":"to take / hold","pin":"ná","char":"拿"},
  {"id":289,"tag":"core","en":"exam / test","pin":"kǎo shì","char":"考试"},
  {"id":290,"tag":"time","en":"yesterday","pin":"zuó tiān","char":"昨天"},
  {"id":291,"tag":"core","en":"to love","pin":"ài","char":"爱"},
  {"id":292,"tag":"core","en":"to want / order / will","pin":"yào","char":"要"},
  {"id":293,"tag":"core","en":"to think / want / miss","pin":"xiǎng","char":"想"},
  {"id":294,"tag":"core","en":"to know (a fact)","pin":"zhī dào","char":"知道"},
  {"id":295,"tag":"core","en":"to know / be acquainted with (a person)","pin":"rèn shi","char":"认识"},
  {"id":296,"tag":"core","en":"they / them","pin":"tā men","char":"他们"},
  {"id":297,"tag":"core","en":"matter / affair (abstract 'thing')","pin":"shì qing","char":"事情"},
  {"id":298,"tag":"core","en":"kilometre","pin":"gōng lǐ","char":"公里"},
  {"id":299,"tag":"core","en":"will / know how to","pin":"huì","char":"会"},
  {"id":300,"tag":"core","en":"to play / have fun","pin":"wán er","char":"玩儿"},
  {"id":301,"tag":"numbers","en":"how many (small number)","pin":"jǐ","char":"几"},
  {"id":302,"tag":"money","en":"how much? (how many yuan)","pin":"jǐ kuài qián？","char":"几块钱？"},
  {"id":303,"tag":"core","en":"how big / how small","pin":"duō dà / duō xiǎo","char":"多大 / 多小"},
  {"id":304,"tag":"sentences","en":"I run to the supermarket; today I'm going for a run","pin":"wǒ pǎo bù qù chāo shì，wǒ jīn tiān qù pǎo bù","char":"我跑步去超市，我今天去跑步"},
  {"id":305,"tag":"sentences","en":"(I) work every day","pin":"měi tiān dōu gōng zuò","char":"每天都工作"},
  {"id":306,"tag":"sentences","en":"It rained yesterday","pin":"zuó tiān xià yǔ le","char":"昨天下雨了"},
  {"id":307,"tag":"sentences","en":"I love eating cake","pin":"wǒ ài chī dàn gāo","char":"我爱吃蛋糕"},
  {"id":308,"tag":"sentences","en":"I love small dogs / big dogs","pin":"wǒ ài xiǎo gǒu / dà gǒu","char":"我爱小狗 / 大狗"},
  {"id":309,"tag":"sentences","en":"I like you","pin":"wǒ xǐ huān nǐ","char":"我喜欢你"},
  {"id":310,"tag":"sentences","en":"I've known them for two years","pin":"wǒ rèn shi tā men liǎng nián le","char":"我认识他们两年了"},
  {"id":311,"tag":"sentences","en":"I know a lot about my dad","pin":"wǒ zhī dào wǒ bà ba de hěn duō shì qing","char":"我知道我爸爸的很多事情"},
  {"id":312,"tag":"sentences","en":"I will go running","pin":"wǒ huì qù pǎo bù","char":"我会去跑步"},
  {"id":313,"tag":"sentences","en":"I can run 20 km","pin":"wǒ néng pǎo èr shí gōng lǐ","char":"我能跑20公里"},
  {"id":314,"tag":"sentences","en":"I can cook (know how to)","pin":"wǒ huì zuò fàn","char":"我会做饭"},
  {"id":315,"tag":"sentences","en":"I can drive","pin":"wǒ huì kāi chē","char":"我会开车"},
  {"id":316,"tag":"core","en":"to walk / go","pin":"zǒu","char":"走"},
  {"id":317,"tag":"core","en":"to study","pin":"xué xí","char":"学习"},
  {"id":318,"tag":"core","en":"to attend school","pin":"shàng xué","char":"上学"},
  {"id":319,"tag":"core","en":"mahjong","pin":"má jiàng","char":"麻将"},
  {"id":320,"tag":"core","en":"to get / obtain","pin":"dé","char":"得"},
  {"id":321,"tag":"core","en":"it","pin":"tā","char":"它"},
  {"id":322,"tag":"core","en":"tired","pin":"lèi","char":"累"},
  {"id":323,"tag":"core","en":"many / much","pin":"duō","char":"多"},
  {"id":324,"tag":"time","en":"hour","pin":"xiǎo shí","char":"小时"},
  {"id":325,"tag":"core","en":"to rest","pin":"xiū xi","char":"休息"},
  {"id":326,"tag":"places","en":"platform (station)","pin":"zhàn tái","char":"站台"},
  {"id":327,"tag":"core","en":"ordinal prefix (第一 = first, 第二 = second)","pin":"dì","char":"第"},
  {"id":328,"tag":"time","en":"years old (age)","pin":"suì","char":"岁"},
  {"id":329,"tag":"food","en":"dumplings","pin":"jiǎo zi","char":"饺子"},
  {"id":330,"tag":"core","en":"kilogram","pin":"gōng jīn","char":"公斤"},
  {"id":331,"tag":"food","en":"sugar / sweets","pin":"táng","char":"糖"},
  {"id":332,"tag":"core","en":"catty (500 g)","pin":"jīn","char":"斤"},
  {"id":333,"tag":"core","en":"every time","pin":"měi cì","char":"每次"},
  {"id":334,"tag":"clothing","en":"top / upper garment","pin":"shàng yī","char":"上衣"},
  {"id":335,"tag":"clothing","en":"trousers","pin":"kù zi","char":"裤子"},
  {"id":336,"tag":"clothing","en":"underpants","pin":"nèi kù","char":"内裤"},
  {"id":337,"tag":"clothing","en":"underwear (top)","pin":"nèi yī","char":"内衣"},
  {"id":338,"tag":"clothing","en":"coat / jacket","pin":"wài tào","char":"外套"},
  {"id":339,"tag":"core","en":"car / vehicle","pin":"chē","char":"车"},
  {"id":340,"tag":"core","en":"happy / pleased","pin":"gāo xìng","char":"高兴"},
  {"id":341,"tag":"core","en":"happy / glad","pin":"kāi xīn","char":"开心"},
  {"id":342,"tag":"core","en":"new","pin":"xīn","char":"新"},
  {"id":343,"tag":"core","en":"heart","pin":"xīn","char":"心"},
  {"id":344,"tag":"core","en":"to use","pin":"yòng","char":"用"},
  {"id":345,"tag":"core","en":"to come","pin":"lái","char":"来"},
  {"id":346,"tag":"core","en":"don't (imperative)","pin":"bié","char":"别"},
  {"id":347,"tag":"phrases","en":"don't worry / calm down","pin":"bié zháo jí","char":"别着急"},
  {"id":348,"tag":"core","en":"very / extremely","pin":"fēi cháng","char":"非常"},
  {"id":349,"tag":"core","en":"far","pin":"yuǎn","char":"远"},
  {"id":350,"tag":"core","en":"still have / also / there's still","pin":"hái yǒu","char":"还有"},
  {"id":351,"tag":"core","en":"to / arrive / until","pin":"dào","char":"到"},
  {"id":352,"tag":"core","en":"still / also / yet","pin":"hái","char":"还"},
  {"id":353,"tag":"core","en":"most (superlative)","pin":"zuì","char":"最"},
  {"id":354,"tag":"slang","en":"really?","pin":"zhēn de ma？","char":"真的吗？"},
  {"id":355,"tag":"core","en":"to draw / a painting","pin":"huà","char":"画"},
  {"id":356,"tag":"core","en":"together","pin":"yì qǐ","char":"一起"},
  {"id":357,"tag":"core","en":"at / in / (progressive -ing)","pin":"zài","char":"在"},
  {"id":358,"tag":"core","en":"again","pin":"zài","char":"再"},
  {"id":359,"tag":"phrases","en":"it's nothing / no worries","pin":"méi shì","char":"没事"},
  {"id":360,"tag":"core","en":"time","pin":"shí jiān","char":"时间"},
  {"id":361,"tag":"core","en":"because","pin":"yīn wèi","char":"因为"},
  {"id":362,"tag":"core","en":"thirsty","pin":"kě","char":"渴"},
  {"id":363,"tag":"places","en":"company / office","pin":"gōng sī","char":"公司"},
  {"id":364,"tag":"phrases","en":"right? / isn't it?","pin":"duì bú duì？","char":"对不对？"},
  {"id":365,"tag":"food","en":"cold dish","pin":"liáng cài","char":"凉菜"},
  {"id":366,"tag":"core","en":"towards","pin":"xiàng","char":"向"},
  {"id":367,"tag":"phrases","en":"not bad / pretty good","pin":"bú cuò","char":"不错"},
  {"id":368,"tag":"phrases","en":"let's go","pin":"zǒu ba","char":"走吧"},
  {"id":369,"tag":"phrases","en":"go away","pin":"zǒu kāi","char":"走开"},
  {"id":370,"tag":"places","en":"Spain","pin":"xī bān yá","char":"西班牙"},
  {"id":371,"tag":"core","en":"(distance / time) from","pin":"lí","char":"离"},
  {"id":372,"tag":"core","en":"birthday","pin":"shēng rì","char":"生日"},
  {"id":373,"tag":"core","en":"metre","pin":"mǐ","char":"米"},
  {"id":374,"tag":"core","en":"to set off / depart","pin":"chū fā","char":"出发"},
  {"id":375,"tag":"core","en":"how far","pin":"duō yuǎn","char":"多远"},
  {"id":376,"tag":"time","en":"minute","pin":"fēn zhōng","char":"分钟"},
  {"id":377,"tag":"core","en":"to walk (on foot)","pin":"zǒu lù","char":"走路"},
  {"id":378,"tag":"core","en":"slow","pin":"màn","char":"慢"},
  {"id":379,"tag":"clothing","en":"red (colour)","pin":"hóng sè","char":"红色"},
  {"id":380,"tag":"core","en":"colour","pin":"sè","char":"色"},
  {"id":381,"tag":"places","en":"hospital","pin":"yī yuàn","char":"医院"},
  {"id":382,"tag":"core","en":"everyone","pin":"měi ge rén","char":"每个人"},
  {"id":383,"tag":"core","en":"verb + 得 + adj (describes how well an action is done)","pin":"V + de + adj","char":"V + 得 + adj"},
  {"id":384,"tag":"core","en":"as soon as … (then) …","pin":"yī … jiù …","char":"一…就…"},
  {"id":385,"tag":"core","en":"want a thing (想要+noun) vs want to do (想+verb)","pin":"xiǎng yào + noun / xiǎng + verb","char":"想要+名词 / 想+动词"},
  {"id":386,"tag":"sentences","en":"They are playing mahjong","pin":"tā men zhèng zài dǎ má jiàng","char":"他们正在打麻将"},
  {"id":387,"tag":"sentences","en":"He plays very well","pin":"tā dǎ de hěn hǎo","char":"他打得很好"},
  {"id":388,"tag":"sentences","en":"He runs fast","pin":"tā pǎo de kuài","char":"他跑得快"},
  {"id":389,"tag":"sentences","en":"He walks slowly","pin":"tā zǒu de màn","char":"他走得慢"},
  {"id":390,"tag":"sentences","en":"Everyone goes to school","pin":"měi ge rén dōu qù xué xiào","char":"每个人都去学校"},
  {"id":391,"tag":"sentences","en":"I drink coffee every day","pin":"wǒ měi tiān dōu hē kā fēi","char":"我每天都喝咖啡"},
  {"id":392,"tag":"sentences","en":"Why do you drink coffee every day?","pin":"wèi shén me nǐ měi tiān dōu hē kā fēi？","char":"为什么你每天都喝咖啡？"},
  {"id":393,"tag":"sentences","en":"Why are you tired every day?","pin":"wèi shén me nǐ měi tiān dōu hěn lèi？","char":"为什么你每天都很累？"},
  {"id":394,"tag":"sentences","en":"Yesterday I started work at 8am","pin":"wǒ zuó tiān zǎo shàng bā diǎn shàng bān","char":"我昨天早上八点上班"},
  {"id":395,"tag":"sentences","en":"Today I finished work at 9am","pin":"wǒ jīn tiān zǎo shàng jiǔ diǎn xià bān","char":"我今天早上九点下班"},
  {"id":396,"tag":"sentences","en":"I worked 25 hours","pin":"wǒ gōng zuò le èr shí wǔ xiǎo shí","char":"我工作了25小时"},
  {"id":397,"tag":"sentences","en":"At noon I rested for two hours","pin":"zhōng wǔ xiū xi le liǎng xiǎo shí","char":"中午休息了两小时"},
  {"id":398,"tag":"sentences","en":"Where is platform 1?","pin":"dì yī zhàn tái zài nǎ lǐ？","char":"第一站台在哪里？"},
  {"id":399,"tag":"sentences","en":"I want the second apple","pin":"wǒ xiǎng yào dì èr ge píng guǒ","char":"我想要第二个苹果"},
  {"id":400,"tag":"sentences","en":"How old are you? I'm 36","pin":"nǐ duō dà le？wǒ sān shí liù suì","char":"你多大了？我36岁"},
  {"id":401,"tag":"sentences","en":"Do you have a dictionary?","pin":"nǐ yǒu yì běn zì diǎn ma？","char":"你有一本字典吗？"},
  {"id":402,"tag":"sentences","en":"I'm reading a book","pin":"wǒ kàn yì běn shū","char":"我看一本书"},
  {"id":403,"tag":"sentences","en":"I eat some cake","pin":"wǒ chī yì xiē dàn gāo","char":"我吃一些蛋糕"},
  {"id":404,"tag":"sentences","en":"How much is this cup?","pin":"zhè ge bēi zi duō shǎo qián？","char":"这个杯子多少钱？"},
  {"id":405,"tag":"sentences","en":"This cup is 6 yuan","pin":"zhè ge bēi zi liù kuài qián","char":"这个杯子六块钱"},
  {"id":406,"tag":"sentences","en":"How many times have you been to China?","pin":"nǐ qù le zhōng guó duō shǎo cì？","char":"你去了中国多少次？"},
  {"id":407,"tag":"sentences","en":"I've been to China three times","pin":"wǒ qù le zhōng guó sān cì","char":"我去了中国三次"},
  {"id":408,"tag":"sentences","en":"How many kilos of sugar do you want?","pin":"nǐ xiǎng yào duō shǎo gōng jīn táng？","char":"你想要多少公斤糖？"},
  {"id":409,"tag":"sentences","en":"I want one and a half jin","pin":"wǒ xiǎng yào yī jīn bàn","char":"我想要一斤半"},
  {"id":410,"tag":"sentences","en":"How much per jin?","pin":"yī jīn duō shǎo qián？","char":"一斤多少钱？"},
  {"id":411,"tag":"sentences","en":"I go to the shop to buy three items of clothing","pin":"wǒ qù shāng diàn mǎi sān jiàn yī fu","char":"我去商店买三件衣服"},
  {"id":412,"tag":"sentences","en":"There's nothing I don't like","pin":"wǒ méi yǒu bù xǐ huān de","char":"我没有不喜欢的"},
  {"id":413,"tag":"sentences","en":"I like them all","pin":"wǒ dōu xǐ huān","char":"我都喜欢"},
  {"id":414,"tag":"sentences","en":"I don't have a car","pin":"wǒ méi yǒu chē","char":"我没有车"},
  {"id":415,"tag":"sentences","en":"I'm fine, not tired anymore","pin":"wǒ hěn hǎo，bú lèi le","char":"我很好，不累了"},
  {"id":416,"tag":"sentences","en":"Don't get this coffee, it doesn't taste good","pin":"nǐ bié yào zhè ge kā fēi，tā bù hǎo hē","char":"你别要这个咖啡，它不好喝"},
  {"id":417,"tag":"sentences","en":"I'm extremely hungry","pin":"wǒ fēi cháng è","char":"我非常饿"},
  {"id":418,"tag":"sentences","en":"The train station is very far","pin":"huǒ chē zhàn fēi cháng yuǎn","char":"火车站非常远"},
  {"id":419,"tag":"sentences","en":"How many hours do you have left?","pin":"nǐ hái yǒu jǐ xiǎo shí？","char":"你还有几小时？"},
  {"id":420,"tag":"sentences","en":"I have two hours until I finish work","pin":"wǒ hái yǒu liǎng xiǎo shí xià bān","char":"我还有两小时下班"},
  {"id":421,"tag":"sentences","en":"He/she is the best-looking","pin":"tā shì zuì hǎo kàn de","char":"他是最好看的"},
  {"id":422,"tag":"sentences","en":"This coffee is the best-tasting","pin":"zhè ge kā fēi shì zuì hǎo hē de","char":"这个咖啡是最好喝的"},
  {"id":423,"tag":"sentences","en":"on the table","pin":"zài zhuō zi shàng","char":"在桌子上"},
  {"id":424,"tag":"sentences","en":"It's real / true","pin":"tā shì zhēn de","char":"它是真的"},
  {"id":425,"tag":"sentences","en":"I'm cooking","pin":"wǒ zài zuò fàn","char":"我在做饭"},
  {"id":426,"tag":"sentences","en":"Let's go eat together","pin":"wǒ men yì qǐ qù chī fàn","char":"我们一起去吃饭"},
  {"id":427,"tag":"sentences","en":"If you have no money, then don't buy it","pin":"nǐ méi yǒu qián，jiù bù mǎi tā","char":"你没有钱，就不买它"},
  {"id":428,"tag":"sentences","en":"If you have no time, then don't go","pin":"nǐ méi yǒu shí jiān，jiù bú qù","char":"你没有时间，就不去"},
  {"id":429,"tag":"sentences","en":"As soon as I start work, I'm tired","pin":"yí shàng bān jiù hěn lèi","char":"一上班就很累"},
  {"id":430,"tag":"sentences","en":"As soon as (I'm) hungry, (I) eat","pin":"yí è jiù chī fàn","char":"一饿就吃饭"},
  {"id":431,"tag":"sentences","en":"Because it's delicious","pin":"yīn wèi tā hěn hǎo chī","char":"因为它很好吃"},
  {"id":432,"tag":"sentences","en":"I got thirsty, so I went to the restaurant to buy coffee","pin":"wǒ kě le，suǒ yǐ wǒ qù fàn guǎn mǎi kā fēi","char":"我渴了，所以我去饭馆买咖啡"},
  {"id":433,"tag":"sentences","en":"I'm hot because I drank coffee","pin":"wǒ hěn rè，yīn wèi wǒ hē le kā fēi","char":"我很热，因为我喝了咖啡"},
  {"id":434,"tag":"sentences","en":"I want to go eat, but I don't have time","pin":"wǒ xiǎng qù chī fàn，dàn shì méi yǒu shí jiān","char":"我想去吃饭，但是没有时间"},
  {"id":435,"tag":"sentences","en":"I want to buy clothes, but I have no money","pin":"wǒ xiǎng mǎi yí jiàn yī fu，dàn shì wǒ méi yǒu qián","char":"我想买一件衣服，但是我没有钱"},
  {"id":436,"tag":"sentences","en":"I go home from the office","pin":"wǒ cóng gōng sī huí jiā","char":"我从公司回家"},
  {"id":437,"tag":"sentences","en":"I work from 1 to 3 o'clock","pin":"wǒ cóng yī diǎn dào sān diǎn gōng zuò","char":"我从一点到三点工作"},
  {"id":438,"tag":"sentences","en":"For me, this coffee is too hot","pin":"duì wǒ lái shuō，zhè bēi kā fēi tài rè le","char":"对我来说，这杯咖啡太热了"},
  {"id":439,"tag":"sentences","en":"For you, this iced tea is too cold, right?","pin":"duì nǐ lái shuō，zhè bēi bīng chá tài liáng le，duì bú duì？","char":"对你来说，这杯冰茶太凉了，对不对？"},
  {"id":440,"tag":"sentences","en":"You turn left / walk to the left","pin":"nǐ xiàng zuǒ zǒu","char":"你向左走"},
  {"id":441,"tag":"sentences","en":"If you want to go to the restaurant, turn left","pin":"nǐ xiǎng yào qù fàn guǎn，jiù xiàng zuǒ zǒu","char":"你想要去饭馆，就向左走"},
  {"id":442,"tag":"sentences","en":"Are you leaving?","pin":"nǐ yào lí kāi ma？","char":"你要离开吗？"},
  {"id":443,"tag":"sentences","en":"I went to Spain on Sunday, but I have to leave because I work on Monday","pin":"wǒ xīng qī tiān qù le xī bān yá，dàn shì wǒ yào lí kāi，yīn wèi wǒ xīng qī yī yào gōng zuò","char":"我星期天去了西班牙，但是我要离开，因为我星期一要工作"},
  {"id":444,"tag":"sentences","en":"There are still 8 days until my birthday","pin":"lí wǒ de shēng rì hái yǒu bā tiān","char":"离我的生日还有八天"},
  {"id":445,"tag":"sentences","en":"There are still 5 metres to the hospital","pin":"lí yī yuàn hái yǒu wǔ mǐ","char":"离医院还有五米"},
  {"id":446,"tag":"sentences","en":"How far is your home from the company?","pin":"nǐ de jiā lí gōng sī duō yuǎn？","char":"你的家离公司多远？"},
  {"id":447,"tag":"sentences","en":"run for 30 minutes","pin":"pǎo bù sān shí fēn zhōng","char":"跑步三十分钟"},
  {"id":448,"tag":"sentences","en":"walk for an hour","pin":"zǒu lù yí ge xiǎo shí","char":"走路一个小时"},
  {"id":449,"tag":"sentences","en":"I won a cup","pin":"wǒ dé le yí ge bēi zi","char":"我得了一个杯子"},
  {"id":450,"tag":"sentences","en":"I got 100 yuan","pin":"wǒ dé le yì bǎi kuài qián","char":"我得了100块钱"},
  {"id":451,"tag":"sentences","en":"I must go to the hospital","pin":"wǒ děi qù yī yuàn","char":"我得去医院"},
  {"id":452,"tag":"sentences","en":"I have to go now","pin":"wǒ děi zǒu le","char":"我得走了"},
  {"id":453,"tag":"sentences","en":"to the left / forward / up","pin":"xiàng zuǒ / xiàng qián / xiàng shàng","char":"向左 / 向前 / 向上"},
  {"id":454,"tag":"core","en":"or (in a statement)","pin":"huò zhě","char":"或者"},
  {"id":455,"tag":"objects","en":"television","pin":"diàn shì","char":"电视"},
  {"id":456,"tag":"food","en":"water","pin":"shuǐ","char":"水"},
  {"id":457,"tag":"food","en":"tea","pin":"chá","char":"茶"},
  {"id":458,"tag":"food","en":"dish / vegetable / food","pin":"cài","char":"菜"},
  {"id":459,"tag":"core","en":"film / movie","pin":"diàn yǐng","char":"电影"},
  {"id":460,"tag":"phrases","en":"interesting / fun","pin":"yǒu yì si","char":"有意思"},
  {"id":461,"tag":"phrases","en":"boring","pin":"méi yì si","char":"没意思"},
  {"id":462,"tag":"places","en":"city","pin":"chéng shì","char":"城市"},
  {"id":463,"tag":"core","en":"which (one)","pin":"nǎ ge","char":"哪个"},
  {"id":464,"tag":"food","en":"bread","pin":"miàn bāo","char":"面包"},
  {"id":465,"tag":"core","en":"is not","pin":"bú shì","char":"不是"},
  {"id":466,"tag":"core","en":"verb + 着 (zhe) — ongoing action / continuing state","pin":"V + zhe","char":"V + 着"},
  {"id":467,"tag":"core","en":"verb + 过 (guò) — have done sth before (experience)","pin":"V + guò","char":"V + 过"},
  {"id":468,"tag":"core","en":"A-not-A question: verb + 不 + verb = yes/no question","pin":"V + bù + V","char":"V + 不 + V"},
  {"id":469,"tag":"phrases","en":"OK? / alright? / good or not?","pin":"hǎo bù hǎo？","char":"好不好？"},
  {"id":470,"tag":"phrases","en":"is that so? / right? / yes, that's right","pin":"shì ma？/ shì ba / shì de","char":"是吗？/ 是吧 / 是的"},
  {"id":471,"tag":"sentences","en":"Did you sleep well?","pin":"nǐ shuì de hǎo bù hǎo？","char":"你睡得好不好？"},
  {"id":472,"tag":"sentences","en":"How did you sleep?","pin":"nǐ shuì de zěn me yàng？","char":"你睡得怎么样？"},
  {"id":473,"tag":"sentences","en":"I'm watching TV","pin":"wǒ kàn zhe diàn shì ne","char":"我看着电视呢"},
  {"id":474,"tag":"sentences","en":"I'm drinking water","pin":"wǒ hē zhe shuǐ ne","char":"我喝着水呢"},
  {"id":475,"tag":"sentences","en":"I'm drinking water and watching TV","pin":"wǒ hē zhe shuǐ，kàn zhe diàn shì","char":"我喝着水，看着电视"},
  {"id":476,"tag":"sentences","en":"I'm eating breakfast and drinking tea","pin":"wǒ chī zhe zǎo fàn，hē zhe chá","char":"我吃着早饭，喝着茶"},
  {"id":477,"tag":"sentences","en":"I'm eating breakfast while doing things","pin":"wǒ chī zhe zǎo fàn，zuò zhe shì qing","char":"我吃着早饭，做着事情"},
  {"id":478,"tag":"sentences","en":"I've had this dish, it's delicious","pin":"wǒ chī guò zhè ge cài，hěn hǎo chī","char":"我吃过这个菜，很好吃"},
  {"id":479,"tag":"sentences","en":"I've seen this movie, it's good","pin":"wǒ kàn guò zhè ge diàn yǐng，hěn hǎo kàn","char":"我看过这个电影，很好看"},
  {"id":480,"tag":"sentences","en":"I've been to China, it's very interesting","pin":"wǒ qù guò zhōng guó，hěn yǒu yì si","char":"我去过中国，很有意思"},
  {"id":481,"tag":"sentences","en":"Let's go to China","pin":"wǒ men qù zhōng guó ba","char":"我们去中国吧"},
  {"id":482,"tag":"sentences","en":"This is your dad, right?","pin":"zhè shì nǐ de bà ba ba？","char":"这是你的爸爸吧？"},
  {"id":483,"tag":"sentences","en":"I looked — it's not","pin":"wǒ kàn le，bú shì","char":"我看了，不是"},
  {"id":484,"tag":"sentences","en":"Where is your school?","pin":"nǐ de xué xiào zài nǎ lǐ？","char":"你的学校在哪里？"},
  {"id":485,"tag":"sentences","en":"Which city?","pin":"nǎ ge chéng shì？","char":"哪个城市？"},
  {"id":486,"tag":"sentences","en":"How many breads do you eat?","pin":"nǐ chī jǐ ge miàn bāo？","char":"你吃几个面包？"},
  {"id":487,"tag":"sentences","en":"I eat two breads, so I buy two","pin":"wǒ chī liǎng ge miàn bāo，suǒ yǐ mǎi liǎng ge","char":"我吃两个面包，所以买两个"},
  {"id":488,"tag":"sentences","en":"How far is the hospital from the restaurant?","pin":"yī yuàn lí fàn guǎn yǒu duō yuǎn？","char":"医院离饭馆有多远？"},
  {"id":489,"tag":"sentences","en":"About a 30-minute walk","pin":"zǒu lù sān shí fēn zhōng ba","char":"走路三十分钟吧"},
  {"id":490,"tag":"sentences","en":"Too far","pin":"tài yuǎn le","char":"太远了"},
  {"id":491,"tag":"sentences","en":"Are you going (or not)?","pin":"nǐ qù bú qù？","char":"你去不去？"},
  {"id":492,"tag":"core","en":"internet / network","pin":"wǎng luò","char":"网络"},
  {"id":493,"tag":"core","en":"middle / in between","pin":"zhōng jiān","char":"中间"},
  {"id":494,"tag":"phrases","en":"OK / sure","pin":"hǎo de","char":"好的"},
  {"id":495,"tag":"core","en":"to have a holiday / go on vacation","pin":"fàng jià","char":"放假"},
  {"id":496,"tag":"core","en":"to travel / tour","pin":"lǚ yóu","char":"旅游"},
  {"id":497,"tag":"core","en":"other / another / else","pin":"bié de","char":"别的"},
  {"id":498,"tag":"phrases","en":"how nice / that's great","pin":"zhēn hǎo","char":"真好"},
  {"id":499,"tag":"core","en":"than (comparison)","pin":"bǐ","char":"比"},
  {"id":500,"tag":"core","en":"Chinese (spoken language)","pin":"hàn yǔ","char":"汉语"},
  {"id":501,"tag":"core","en":"Norwegian (language)","pin":"nuó wēi yǔ","char":"挪威语"},
  {"id":502,"tag":"places","en":"Norway","pin":"nuó wēi","char":"挪威"},
  {"id":503,"tag":"places","en":"classroom","pin":"jiào shì","char":"教室"},
  {"id":504,"tag":"core","en":"before / ago / front","pin":"qián","char":"前"},
  {"id":505,"tag":"core","en":"normal","pin":"zhèng cháng","char":"正常"},
  {"id":506,"tag":"core","en":"above / over (more than)","pin":"yǐ shàng","char":"以上"},
  {"id":507,"tag":"core","en":"below / under (less than)","pin":"yǐ xià","char":"以下"},
  {"id":508,"tag":"places","en":"room","pin":"fáng jiān","char":"房间"},
  {"id":509,"tag":"core","en":"then / afterwards","pin":"rán hòu","char":"然后"},
  {"id":510,"tag":"core","en":"up / on / to attend (上班 = go to work)","pin":"shàng","char":"上"},
  {"id":511,"tag":"time","en":"a few months / how many months","pin":"jǐ ge yuè","char":"几个月"},
  {"id":512,"tag":"core","en":"comparison: A 比 B + adj (A is more … than B)","pin":"A bǐ B + adj","char":"A 比 B + adj"},
  {"id":513,"tag":"sentences","en":"the internet is slow","pin":"wǎng luò hěn màn","char":"网络很慢"},
  {"id":514,"tag":"sentences","en":"No — let's meet at the restaurant at 3","pin":"bù，sān diǎn fàn guǎn jiàn ba","char":"不，三点饭馆见吧"},
  {"id":515,"tag":"sentences","en":"Will you take a holiday back to China next year?","pin":"nǐ míng nián huì fàng jià huí zhōng guó ma？","char":"你明年会放假回中国吗？"},
  {"id":516,"tag":"sentences","en":"He is 4 years older than me","pin":"tā bǐ wǒ dà sì suì","char":"他比我大四岁"},
  {"id":517,"tag":"sentences","en":"Does he speak Chinese?","pin":"tā shuō zhōng wén ma？","char":"他说中文吗？"},
  {"id":518,"tag":"sentences","en":"A long time ago, I went to the classroom","pin":"tài jiǔ qián，wǒ qù le jiào shì","char":"太久前，我去了教室"},
  {"id":519,"tag":"sentences","en":"How long ago?","pin":"duō jiǔ qián？","char":"多久前？"},
  {"id":520,"tag":"sentences","en":"ten years ago","pin":"shí nián qián","char":"十年前"},
  {"id":521,"tag":"sentences","en":"For people over 40, it's normal","pin":"duì sì shí suì yǐ shàng de rén lái shuō，hěn zhèng cháng","char":"对四十岁以上的人来说，很正常"},
  {"id":522,"tag":"sentences","en":"For people under 40, it's not normal","pin":"duì sì shí suì yǐ xià de rén lái shuō，bú zhèng cháng","char":"对四十岁以下的人来说，不正常"},
  {"id":523,"tag":"sentences","en":"One or two rooms is quite normal","pin":"yí ge fáng jiān huò zhě liǎng ge fáng jiān hěn zhèng cháng","char":"一个房间或者两个房间很正常"},
  {"id":524,"tag":"core","en":"meeting","pin":"huì yì","char":"会议"},
  {"id":525,"tag":"core","en":"front / in front","pin":"qián miàn","char":"前面"},
  {"id":526,"tag":"core","en":"back / behind","pin":"hòu miàn","char":"后面"},
  {"id":527,"tag":"core","en":"only","pin":"zhǐ","char":"只"},
  {"id":528,"tag":"core","en":"to go out (the door)","pin":"chū mén","char":"出门"},
  {"id":529,"tag":"core","en":"side","pin":"biān","char":"边"},
  {"id":530,"tag":"core","en":"left(-hand) side","pin":"zuǒ biān","char":"左边"},
  {"id":531,"tag":"core","en":"right(-hand) side","pin":"yòu biān","char":"右边"},
  {"id":532,"tag":"core","en":"who","pin":"shéi","char":"谁"},
  {"id":533,"tag":"core","en":"friend","pin":"péng yǒu","char":"朋友"},
  {"id":534,"tag":"core","en":"last / final","pin":"zuì hòu","char":"最后"},
  {"id":535,"tag":"core","en":"to lose","pin":"shī qù","char":"失去"},
  {"id":536,"tag":"core","en":"sad / heartbroken","pin":"shāng xīn","char":"伤心"},
  {"id":537,"tag":"core","en":"only (have)","pin":"zhǐ yǒu","char":"只有"},
  {"id":538,"tag":"core","en":"beside / next to","pin":"páng biān","char":"旁边"},
  {"id":539,"tag":"time","en":"tomorrow","pin":"míng tiān","char":"明天"},
  {"id":540,"tag":"core","en":"to fly","pin":"fēi","char":"飞"},
  {"id":541,"tag":"places","en":"London","pin":"lún dūn","char":"伦敦"},
  {"id":542,"tag":"sentences","en":"Next month I'm going to Spain","pin":"wǒ xià ge yuè qù xī bān yá","char":"我下个月去西班牙"},
  {"id":543,"tag":"sentences","en":"I'll go to a Spanish restaurant","pin":"wǒ huì qù xī bān yá fàn guǎn","char":"我会去西班牙饭馆"},
  {"id":544,"tag":"sentences","en":"The Korean restaurant is in front of my house","pin":"hán guó fàn guǎn zài wǒ de jiā qián miàn","char":"韩国饭馆在我的家前面"},
  {"id":545,"tag":"sentences","en":"Only in front of my house, none behind","pin":"zhǐ zài wǒ de jiā qián miàn，zài hòu miàn méi yǒu","char":"只在我的家前面，在后面没有"},
  {"id":546,"tag":"sentences","en":"If you want to go to the shop, after going out, turn left","pin":"nǐ xiǎng yào qù shāng diàn，chū mén hòu，nǐ xiàng zuǒ biān zǒu","char":"你想要去商店，出门后，你向左边走"},
  {"id":547,"tag":"sentences","en":"If you want to go to the train station, after going out, turn right","pin":"nǐ xiǎng yào qù huǒ chē zhàn，chū mén hòu，nǐ xiàng yòu biān zǒu","char":"你想要去火车站，出门后，你向右边走"},
  {"id":548,"tag":"sentences","en":"There are still 8 minutes to the train station","pin":"lí huǒ chē zhàn hái yǒu bā fēn zhōng","char":"离火车站还有八分钟"},
  {"id":549,"tag":"sentences","en":"We need to run","pin":"wǒ men xū yào pǎo bù","char":"我们需要跑步"},
  {"id":550,"tag":"sentences","en":"Let's go out to eat breakfast at 9","pin":"wǒ men jiǔ diǎn qù wài miàn chī zǎo fàn ba","char":"我们九点去外面吃早饭吧"},
  {"id":551,"tag":"sentences","en":"Who's going with us?","pin":"shéi hé wǒ men yì qǐ qù？","char":"谁和我们一起去？"},
  {"id":552,"tag":"sentences","en":"No one else is going with us, we have no friends","pin":"méi yǒu bié rén hé wǒ men qù，wǒ men méi yǒu péng yǒu","char":"没有别人和我们去，我们没有朋友"},
  {"id":553,"tag":"sentences","en":"You are my last friend","pin":"nǐ shì wǒ zuì hòu yí ge péng yǒu","char":"你是我最后一个朋友"},
  {"id":554,"tag":"sentences","en":"I lost my last friend","pin":"wǒ shī qù le wǒ zuì hòu yí ge péng yǒu","char":"我失去了我最后一个朋友"},
  {"id":555,"tag":"sentences","en":"Too sad","pin":"tài shāng xīn le","char":"太伤心了"},
  {"id":556,"tag":"sentences","en":"Only the two of us","pin":"zhǐ yǒu wǒ men liǎng ge rén","char":"只有我们两个人"},
  {"id":557,"tag":"sentences","en":"I have a car beside my house","pin":"wǒ yǒu chē zài wǒ de jiā páng biān","char":"我有车在我的家旁边"},
  {"id":558,"tag":"sentences","en":"Who's driving? Who's sitting beside you?","pin":"shéi kāi chē？shéi zuò zài nǐ de páng biān？","char":"谁开车？谁坐在你的旁边？"},
  {"id":559,"tag":"sentences","en":"Today it's cold, so we eat at home","pin":"jīn tiān hěn lěng，suǒ yǐ wǒ men zài wǒ de jiā lǐ chī fàn","char":"今天很冷，所以我们在我的家里吃饭"},
  {"id":560,"tag":"sentences","en":"We eat Chinese food because it's delicious","pin":"wǒ men chī zhōng guó cài，yīn wèi zhōng guó cài hěn hǎo chī","char":"我们吃中国菜，因为中国菜很好吃"},
  {"id":561,"tag":"sentences","en":"Tomorrow I fly to America","pin":"míng tiān wǒ zuò fēi jī qù měi guó","char":"明天我坐飞机去美国"},
  {"id":562,"tag":"sentences","en":"I'll come home in two weeks","pin":"wǒ liǎng ge xīng qī hòu huí jiā","char":"我两个星期后回家"},
  {"id":563,"tag":"sentences","en":"Yesterday I flew from Norway to London","pin":"zuó tiān wǒ cóng nuó wēi fēi dào lún dūn","char":"昨天我从挪威飞到伦敦"},
  {"id":564,"tag":"time","en":"Sunday","pin":"zhōu rì","char":"周日"},
  {"id":565,"tag":"food","en":"brunch","pin":"zǎo wǔ fàn","char":"早午饭"},
  {"id":566,"tag":"places","en":"park","pin":"gōng yuán","char":"公园"},
  {"id":567,"tag":"core","en":"fast / quick","pin":"kuài","char":"快"},
  {"id":568,"tag":"core","en":"country","pin":"guó jiā","char":"国家"},
  {"id":569,"tag":"places","en":"Hong Kong","pin":"xiāng gǎng","char":"香港"},
  {"id":570,"tag":"core","en":"moreover / and also","pin":"ér qiě","char":"而且"},
  {"id":571,"tag":"places","en":"Ireland","pin":"ài ěr lán","char":"爱尔兰"},
  {"id":572,"tag":"time","en":"February","pin":"èr yuè","char":"二月"},
  {"id":573,"tag":"time","en":"day of the month / number","pin":"hào","char":"号"},
  {"id":574,"tag":"core","en":"forever","pin":"yǒng yuǎn","char":"永远"},
  {"id":575,"tag":"core","en":"to swim","pin":"yóu yǒng","char":"游泳"},
  {"id":576,"tag":"core","en":"to order (food / drinks)","pin":"diǎn","char":"点"},
  {"id":577,"tag":"sentences","en":"I go running in the late morning; will you go to the park?","pin":"wǒ shàng wǔ qù pǎo bù，nǐ shàng wǔ huì qù gōng yuán ma？","char":"我上午去跑步，你上午会去公园吗？"},
  {"id":578,"tag":"sentences","en":"You can go running with my friend","pin":"nǐ kě yǐ hé wǒ de péng yǒu qù pǎo bù","char":"你可以和我的朋友去跑步"},
  {"id":579,"tag":"sentences","en":"Who all is coming? / Who's there?","pin":"dōu yǒu shéi？","char":"都有谁？"},
  {"id":580,"tag":"sentences","en":"I already have a red T-shirt","pin":"wǒ yǐ jīng yǒu yí jiàn hóng T xù le","char":"我已经有一件红T恤了"},
  {"id":581,"tag":"sentences","en":"This year I've traveled too much","pin":"jīn nián wǒ lǚ yóu tài duō le","char":"今年我旅游太多了"},
  {"id":582,"tag":"sentences","en":"How many countries did you go to this year?","pin":"nǐ jīn nián qù le duō shǎo ge guó jiā？","char":"你今年去了多少个国家？"},
  {"id":583,"tag":"sentences","en":"In February (I) went to Ireland for three days","pin":"èr yuè qù le ài ěr lán sān tiān","char":"二月去了爱尔兰三天"},
  {"id":584,"tag":"sentences","en":"When is your birthday?","pin":"nǐ de shēng rì shì shén me shí hou？","char":"你的生日是什么时候？"},
  {"id":585,"tag":"sentences","en":"March 24th","pin":"sān yuè èr shí sì hào","char":"三月二十四号"},
  {"id":586,"tag":"sentences","en":"two weeks ago","pin":"liǎng ge xīng qī qián","char":"两个星期前"},
  {"id":587,"tag":"sentences","en":"What are you doing this weekend?","pin":"nǐ zhè zhōu mò zuò shén me？","char":"你这周末做什么？"},
  {"id":588,"tag":"sentences","en":"half past one (1:30)","pin":"yī diǎn bàn","char":"一点半"},
  {"id":589,"tag":"sentences","en":"Let's go swimming at 6","pin":"wǒ men liù diǎn qù yóu yǒng ba","char":"我们六点去游泳吧"},
  {"id":590,"tag":"sentences","en":"Which tea will you order?","pin":"nǐ diǎn nǎ ge chá？","char":"你点哪个茶？"},
  {"id":591,"tag":"sentences","en":"I like iced tea, I'll order a cup of iced tea","pin":"wǒ xǐ huān bīng chá，wǒ diǎn yì bēi bīng chá","char":"我喜欢冰茶，我点一杯冰茶"},
  {"id":592,"tag":"time","en":"January","pin":"yī yuè","char":"一月"},
  {"id":593,"tag":"time","en":"March","pin":"sān yuè","char":"三月"},
  {"id":594,"tag":"time","en":"April","pin":"sì yuè","char":"四月"},
  {"id":595,"tag":"time","en":"May","pin":"wǔ yuè","char":"五月"},
  {"id":596,"tag":"time","en":"June","pin":"liù yuè","char":"六月"},
  {"id":597,"tag":"time","en":"July","pin":"qī yuè","char":"七月"},
  {"id":598,"tag":"time","en":"August","pin":"bā yuè","char":"八月"},
  {"id":599,"tag":"time","en":"September","pin":"jiǔ yuè","char":"九月"},
  {"id":600,"tag":"time","en":"October","pin":"shí yuè","char":"十月"},
  {"id":601,"tag":"time","en":"November","pin":"shí yī yuè","char":"十一月"},
  {"id":602,"tag":"time","en":"December","pin":"shí èr yuè","char":"十二月"},
  {"id":603,"tag":"time","en":"month = number + 月 (一月 = Jan … 十二月 = Dec)","pin":"… yuè","char":"数字 + 月"},
  {"id":604,"tag":"time","en":"date = number + 号 (spoken) / 日 (written), e.g. 24th = 二十四号","pin":"… hào / … rì","char":"数字 + 号 / 日"},
  {"id":605,"tag":"time","en":"day / date (formal 日, = spoken 号)","pin":"rì","char":"日"},
  {"id":606,"tag":"core","en":"jet lag / time difference","pin":"shí chā","char":"时差"},
  {"id":607,"tag":"core","en":"drunk","pin":"zuì","char":"醉"},
  {"id":608,"tag":"core","en":"a tiny bit / just a little","pin":"yì diǎn diǎn","char":"一点点"},
  {"id":609,"tag":"core","en":"to wait","pin":"děng","char":"等"},
  {"id":610,"tag":"core","en":"sometimes","pin":"yǒu shí hou","char":"有时候"},
  {"id":611,"tag":"core","en":"never (have)","pin":"cóng lái méi yǒu","char":"从来没有"},
  {"id":612,"tag":"core","en":"to assume / think (mistakenly)","pin":"yǐ wéi","char":"以为"},
  {"id":613,"tag":"core","en":"class / lesson","pin":"kè","char":"课"},
  {"id":614,"tag":"time","en":"Monday","pin":"zhōu yī","char":"周一"},
  {"id":615,"tag":"time","en":"Tuesday","pin":"zhōu èr","char":"周二"},
  {"id":616,"tag":"time","en":"Wednesday","pin":"zhōu sān","char":"周三"},
  {"id":617,"tag":"time","en":"Thursday","pin":"zhōu sì","char":"周四"},
  {"id":618,"tag":"time","en":"Friday","pin":"zhōu wǔ","char":"周五"},
  {"id":619,"tag":"time","en":"Saturday","pin":"zhōu liù","char":"周六"},
  {"id":620,"tag":"time","en":"this week","pin":"zhè zhōu","char":"这周"},
  {"id":621,"tag":"time","en":"next week","pin":"xià zhōu","char":"下周"},
  {"id":622,"tag":"time","en":"last week","pin":"shàng zhōu","char":"上周"},
  {"id":623,"tag":"sentences","en":"How many hours?","pin":"duō shǎo ge xiǎo shí？","char":"多少个小时？"},
  {"id":624,"tag":"phrases","en":"wait for me","pin":"děng wǒ","char":"等我"},
  {"id":625,"tag":"phrases","en":"let me have a look / I'll check","pin":"wǒ kàn kàn","char":"我看看"},
  {"id":626,"tag":"sentences","en":"When did you go to the restaurant?","pin":"nǐ shén me shí hou qù le fàn guǎn？","char":"你什么时候去了饭馆？"},
  {"id":627,"tag":"sentences","en":"You listen to songs while cooking","pin":"nǐ zuò fàn de shí hou tīng gē","char":"你做饭的时候听歌"},
  {"id":628,"tag":"sentences","en":"You sometimes go to the park","pin":"nǐ yǒu shí hou qù gōng yuán","char":"你有时候去公园"},
  {"id":629,"tag":"sentences","en":"Sometimes I eat Korean food, sometimes Chinese food","pin":"wǒ yǒu shí hou chī hán guó cài，yǒu shí hou chī zhōng guó cài","char":"我有时候吃韩国菜，有时候吃中国菜"},
  {"id":630,"tag":"sentences","en":"I've never eaten English food","pin":"wǒ cóng lái méi yǒu chī yīng guó cài","char":"我从来没有吃英国菜"},
  {"id":631,"tag":"sentences","en":"I thought there was a Chinese class at 11pm last night","pin":"wǒ yǐ wéi zuó tiān wǎn shang shí yī diǎn yǒu zhōng wén kè","char":"我以为昨天晚上十一点有中文课"},
  {"id":632,"tag":"sentences","en":"Sometimes I work 8 hours, sometimes 24 hours at the hospital","pin":"wǒ yǒu shí hou gōng zuò bā xiǎo shí，yǒu shí hou zài yī yuàn gōng zuò èr shí sì xiǎo shí","char":"我有时候工作八小时，有时候在医院工作二十四小时"},
  {"id":633,"tag":"sentences","en":"This Fri, this Sun, next Tue are all 24-hour shifts; next week I'll be exhausted","pin":"zhè zhōu wǔ，zhè zhōu tiān，xià zhōu èr dōu shì èr shí sì xiǎo shí，wǒ xià zhōu huì hěn lèi","char":"这周五、这周天、下周二都是二十四小时，我下周会很累"},
  {"id":634,"tag":"sentences","en":"When do you not have time?","pin":"nǐ shén me shí hou méi yǒu shí jiān？","char":"你什么时候没有时间？"},
  {"id":635,"tag":"sentences","en":"I have a little time","pin":"wǒ yǒu yì diǎn shí jiān","char":"我有一点时间"}
]
