export const CARDS = [
  {"id":0,"tag":"sentences","en":"I went to a restaurant with a friend to eat Korean food","pin":"wǒ hé péng yǒu qù fàn guǎn chī hán guó cài","char":"我和朋友去饭馆吃韩国菜"},
  {"id":1,"tag":"sentences","en":"Who did you go with?","pin":"hé shéi qù？","char":"和谁去？"},
  {"id":2,"tag":"core","en":"come back / go back","pin":"huí lai / huí qù","char":"回来 / 回去"},
  {"id":3,"tag":"food","en":"dumplings (boiled)","pin":"shuǐ jiǎo","char":"水饺"},
  {"id":4,"tag":"core","en":"give","pin":"gěi","char":"给"},
  {"id":5,"tag":"sentences","en":"I will call my mum","pin":"wǒ huì gěi wǒ de mā ma dǎ diàn huà","char":"我会给我的妈妈打电话"},
  {"id":6,"tag":"sentences","en":"Will you call me?","pin":"nǐ huì gěi wǒ dǎ diàn huà","char":"你会给我打电话"},
  {"id":7,"tag":"core","en":"sit / take (transport)","pin":"zuò","char":"坐"},
  {"id":8,"tag":"core","en":"do (action)","pin":"zuò","char":"做"},
  {"id":9,"tag":"core","en":"work (noun)","pin":"gōng zuò","char":"工作"},
  {"id":10,"tag":"sentences","en":"What do you do?","pin":"nǐ zuò shén me？","char":"你做什么？"},
  {"id":11,"tag":"sentences","en":"What are you doing right now?","pin":"nǐ zài zuò shén me？","char":"你在做什么？"},
  {"id":12,"tag":"sentences","en":"What can you do?","pin":"nǐ huì zuò shén me？","char":"你会做什么？"},
  {"id":13,"tag":"sentences","en":"Apples are delicious","pin":"píng guǒ hěn hǎo chī","char":"苹果很好吃"},
  {"id":14,"tag":"core","en":"door","pin":"mén","char":"门"},
  {"id":15,"tag":"sentences","en":"What time does it open?","pin":"shén me shí hou kāi mén？","char":"什么时候开门？"},
  {"id":16,"tag":"sentences","en":"It opens at 8 o'clock","pin":"bā diǎn kāi mén","char":"八点开门"},
  {"id":17,"tag":"time","en":"what time?","pin":"jǐ diǎn","char":"几点"},
  {"id":18,"tag":"sentences","en":"I got on the bus","pin":"wǒ zuò shàng chē le","char":"我坐上车了"},
  {"id":19,"tag":"sentences","en":"I got off the bus","pin":"wǒ xià chē le","char":"我下车了"},
  {"id":20,"tag":"core","en":"down / get off","pin":"xià","char":"下"},
  {"id":21,"tag":"sentences","en":"I live in England","pin":"wǒ zhù zài yīng guó","char":"我住在英国"},
  {"id":22,"tag":"core","en":"how long?","pin":"duō jiǔ le","char":"多久了"},
  {"id":23,"tag":"sentences","en":"How long have you lived in England?","pin":"nǐ zhù zài yīng guó duō jiǔ le？","char":"你住在英国多久了？"},
  {"id":24,"tag":"sentences","en":"I have lived in England for six years","pin":"wǒ zhù zài yīng guó liù nián le","char":"我住在英国六年了"},
  {"id":25,"tag":"core","en":"to become","pin":"chéng wéi","char":"成为"},
  {"id":26,"tag":"core","en":"by / through","pin":"tōng guò","char":"通过"},
  {"id":27,"tag":"sentences","en":"I became a doctor through studying","pin":"wǒ tōng guò xué xí chéng wéi le yī shēng","char":"我通过学习成为了医生"},
  {"id":28,"tag":"sentences","en":"I went to work at the hospital","pin":"wǒ qù le yī yuàn gōng zuò","char":"我去了医院工作"},
  {"id":29,"tag":"core","en":"start a shift","pin":"shàng bān","char":"上班"},
  {"id":30,"tag":"sentences","en":"I finished my shift","pin":"wǒ xià bān le","char":"我下班了"},
  {"id":31,"tag":"sentences","en":"I finish work at 6pm","pin":"wǒ xià wǔ liù diǎn xià bān","char":"我下午六点下班"},
  {"id":32,"tag":"sentences","en":"It is raining today","pin":"jīn tiān xià yǔ","char":"今天下雨"},
  {"id":33,"tag":"sentences","en":"He is a teacher","pin":"tā shì lǎo shī","char":"他是老师"},
  {"id":34,"tag":"sentences","en":"I have a dictionary","pin":"wǒ yǒu yī běn zì diǎn","char":"我有一本字典"},
  {"id":35,"tag":"core","en":"this is me","pin":"zhè shì wǒ","char":"这是我"},
  {"id":36,"tag":"core","en":"I am here","pin":"wǒ zài zhèr","char":"我在这儿"},
  {"id":37,"tag":"sentences","en":"Where are you?","pin":"nǐ zài nǎ？","char":"你在哪？"},
  {"id":38,"tag":"sentences","en":"Who are you?","pin":"nǐ shì shéi？","char":"你是谁？"},
  {"id":39,"tag":"sentences","en":"What is this?","pin":"zhè shì shén me？","char":"这是什么？"},
  {"id":40,"tag":"objects","en":"cup","pin":"bēi zi","char":"杯子"},
  {"id":41,"tag":"money","en":"how much?","pin":"duō shǎo qián？","char":"多少钱？"},
  {"id":42,"tag":"money","en":"one yuan","pin":"yī kuài qián","char":"一块钱"},
  {"id":43,"tag":"numbers","en":"hundred","pin":"bǎi","char":"百"},
  {"id":44,"tag":"numbers","en":"thousand","pin":"qiān","char":"千"},
  {"id":45,"tag":"numbers","en":"ten thousand","pin":"wàn","char":"万"},
  {"id":46,"tag":"numbers","en":"100 million","pin":"yì","char":"亿"},
  {"id":47,"tag":"slang","en":"forever (1314)","pin":"yī shēng yí shì","char":"一生一世"},
  {"id":48,"tag":"slang","en":"I love you (520)","pin":"wǒ ài nǐ","char":"我爱你"},
  {"id":49,"tag":"sentences","en":"How old are you?","pin":"nǐ duō dà le？","char":"你多大了？"},
  {"id":50,"tag":"sentences","en":"How do you do this?","pin":"zhè zěn me zuò？","char":"这怎么做？"},
  {"id":51,"tag":"core","en":"and you?","pin":"nǐ ne？","char":"你呢？"},
  {"id":52,"tag":"core","en":"inside","pin":"lǐ","char":"里"},
  {"id":53,"tag":"core","en":"where","pin":"nǎ lǐ / nǎr","char":"哪里 / 哪儿"},
  {"id":54,"tag":"core","en":"when?","pin":"shén me shí hou？","char":"什么时候？"},
  {"id":55,"tag":"food","en":"wine / alcohol","pin":"jiǔ","char":"酒"},
  {"id":56,"tag":"phrases","en":"Happy Birthday","pin":"shēng rì kuài lè","char":"生日快乐"},
  {"id":57,"tag":"phrases","en":"Happy New Year","pin":"xīn nián kuài lè","char":"新年快乐"},
  {"id":58,"tag":"core","en":"happy","pin":"kuài lè","char":"快乐"},
  {"id":59,"tag":"food","en":"cake","pin":"dàn gāo","char":"蛋糕"},
  {"id":60,"tag":"phrases","en":"I don't know","pin":"wǒ bù zhī dào","char":"我不知道"},
  {"id":61,"tag":"core","en":"don't have / didn't","pin":"méi yǒu","char":"没有"},
  {"id":62,"tag":"core","en":"drink","pin":"hē","char":"喝"},
  {"id":63,"tag":"food","en":"coffee","pin":"kā fēi","char":"咖啡"},
  {"id":64,"tag":"core","en":"play / hit / call","pin":"dǎ","char":"打"},
  {"id":65,"tag":"core","en":"delicious","pin":"hěn hǎo chī","char":"很好吃"},
  {"id":66,"tag":"phrases","en":"great!","pin":"tài hǎo le","char":"太好了"},
  {"id":67,"tag":"core","en":"want","pin":"xiǎng yào","char":"想要"},
  {"id":68,"tag":"core","en":"things","pin":"dōng xi","char":"东西"},
  {"id":69,"tag":"core","en":"also","pin":"yě","char":"也"},
  {"id":70,"tag":"sentences","en":"I drank coffee","pin":"wǒ hē le kā fēi","char":"我喝了咖啡"},
  {"id":71,"tag":"phrases","en":"hello (on phone)","pin":"wéi","char":"喂"},
  {"id":72,"tag":"sentences","en":"I go home","pin":"wǒ huí jiā","char":"我回家"},
  {"id":73,"tag":"sentences","en":"Where is your home?","pin":"nǐ de jiā zài nǎ？","char":"你的家在哪？"},
  {"id":74,"tag":"core","en":"other people","pin":"bié rén","char":"别人"},
  {"id":75,"tag":"core","en":"hot","pin":"rè","char":"热"},
  {"id":76,"tag":"core","en":"cold (weather)","pin":"lěng","char":"冷"},
  {"id":77,"tag":"core","en":"cool (food/drink)","pin":"liáng","char":"凉"},
  {"id":78,"tag":"core","en":"ice","pin":"bīng","char":"冰"},
  {"id":79,"tag":"places","en":"train station","pin":"huǒ chē zhàn","char":"火车站"},
  {"id":80,"tag":"core","en":"outside","pin":"wài miàn","char":"外面"},
  {"id":81,"tag":"objects","en":"table","pin":"zhuō zi","char":"桌子"},
  {"id":82,"tag":"objects","en":"phone (mobile)","pin":"shǒu jī","char":"手机"},
  {"id":83,"tag":"objects","en":"computer","pin":"diàn nǎo","char":"电脑"},
  {"id":84,"tag":"sentences","en":"I am inside the house","pin":"wǒ zài jiā lǐ miàn","char":"我在家里面"},
  {"id":85,"tag":"time","en":"midnight – 5am","pin":"líng chén","char":"凌晨"},
  {"id":86,"tag":"time","en":"morning (5–9am)","pin":"zǎo shàng","char":"早上"},
  {"id":87,"tag":"time","en":"late morning (9am–12pm)","pin":"shàng wǔ","char":"上午"},
  {"id":88,"tag":"time","en":"noon","pin":"zhōng wǔ","char":"中午"},
  {"id":89,"tag":"time","en":"afternoon","pin":"xià wǔ","char":"下午"},
  {"id":90,"tag":"time","en":"evening","pin":"wǎn shàng","char":"晚上"},
  {"id":91,"tag":"time","en":"dusk","pin":"bàng wǎn","char":"傍晚"},
  {"id":92,"tag":"food","en":"breakfast","pin":"zǎo fàn","char":"早饭"},
  {"id":93,"tag":"food","en":"lunch","pin":"wǔ fàn","char":"午饭"},
  {"id":94,"tag":"food","en":"dinner","pin":"wǎn fàn","char":"晚饭"},
  {"id":95,"tag":"time","en":"this year","pin":"jīn nián","char":"今年"},
  {"id":96,"tag":"time","en":"next year","pin":"míng nián","char":"明年"},
  {"id":97,"tag":"time","en":"last year","pin":"qù nián","char":"去年"},
  {"id":98,"tag":"time","en":"this month","pin":"zhè ge yuè","char":"这个月"},
  {"id":99,"tag":"time","en":"next month","pin":"xià ge yuè","char":"下个月"},
  {"id":100,"tag":"time","en":"last month","pin":"shàng ge yuè","char":"上个月"},
  {"id":101,"tag":"time","en":"this week","pin":"zhè ge xīng qī","char":"这个星期"},
  {"id":102,"tag":"time","en":"Monday","pin":"xīng qī yī","char":"星期一"},
  {"id":103,"tag":"time","en":"Sunday","pin":"xīng qī tiān","char":"星期天"},
  {"id":104,"tag":"time","en":"weekend","pin":"zhōu mò","char":"周末"},
  {"id":105,"tag":"core","en":"half (time)","pin":"bàn","char":"半"},
  {"id":106,"tag":"sentences","en":"How many minutes do you need?","pin":"nǐ xū yào duō shǎo fēn zhōng？","char":"你需要多少分钟？"},
  {"id":107,"tag":"core","en":"before / previously","pin":"yǐ qián","char":"以前"},
  {"id":108,"tag":"core","en":"after / later","pin":"hòu","char":"后"},
  {"id":109,"tag":"sentences","en":"in 5 minutes","pin":"wǔ fēn zhōng hòu","char":"五分钟后"},
  {"id":110,"tag":"sentences","en":"What time is it now?","pin":"xiàn zài shì jǐ diǎn？","char":"现在是几点？"},
  {"id":111,"tag":"time","en":"one week ago","pin":"yì zhōu qián","char":"一周前"},
  {"id":112,"tag":"core","en":"already","pin":"yǐ jīng","char":"已经"},
  {"id":113,"tag":"clothing","en":"clothes","pin":"yī fu","char":"衣服"},
  {"id":114,"tag":"clothing","en":"red","pin":"hóng","char":"红"},
  {"id":115,"tag":"clothing","en":"T-shirt","pin":"T xù","char":"T恤"},
  {"id":116,"tag":"clothing","en":"short sleeve","pin":"duǎn xiù","char":"短袖"},
  {"id":117,"tag":"clothing","en":"long sleeve","pin":"cháng xiù","char":"长袖"},
  {"id":118,"tag":"clothing","en":"wear","pin":"chuān","char":"穿"},
  {"id":119,"tag":"places","en":"school","pin":"xué xiào","char":"学校"},
  {"id":120,"tag":"core","en":"some","pin":"yì xiē","char":"一些"},
  {"id":121,"tag":"core","en":"eat food","pin":"chī fàn","char":"吃饭"},
  {"id":122,"tag":"core","en":"or (in a question)","pin":"hái shì","char":"还是"},
  {"id":123,"tag":"objects","en":"plate","pin":"pán zi","char":"盘子"},
  {"id":124,"tag":"core","en":"ok / can / may","pin":"kě yǐ","char":"可以"},
  {"id":125,"tag":"core","en":"often","pin":"jīng cháng","char":"经常"},
  {"id":126,"tag":"sentences","en":"How is the weather today?","pin":"jīn tiān tiān qì zěn me yàng？","char":"今天天气怎么样？"},
  {"id":127,"tag":"music","en":"music","pin":"yīn yuè","char":"音乐"},
  {"id":128,"tag":"music","en":"song","pin":"gē","char":"歌"},
  {"id":129,"tag":"sentences","en":"I am listening to a song","pin":"wǒ zài tīng gē","char":"我在听歌"},
  {"id":130,"tag":"core","en":"sunset","pin":"rì luò","char":"日落"},
  {"id":131,"tag":"core","en":"right? (tag question)","pin":"ba","char":"吧"},
  {"id":132,"tag":"core","en":"name","pin":"míng zi","char":"名字"},
  {"id":133,"tag":"sentences","en":"What is your name?","pin":"nǐ jiào shén me míng zi？","char":"你叫什么名字？"},
  {"id":134,"tag":"core","en":"come here","pin":"guò lai","char":"过来"},
  {"id":135,"tag":"core","en":"times (occurrences)","pin":"cì","char":"次"},
  {"id":136,"tag":"sentences","en":"I like eating fruit","pin":"wǒ xǐ huān chī shuǐ guǒ","char":"我喜欢吃水果"},
  {"id":137,"tag":"phrases","en":"no need","pin":"bú yòng","char":"不用"},
  {"id":138,"tag":"phrases","en":"you're welcome","pin":"bié kè qi","char":"别客气"},
  {"id":139,"tag":"sentences","en":"next year I'll fly to China","pin":"míng nián wǒ zuò fēi jī qù zhōng guó","char":"明年我坐飞机去中国"},
  {"id":140,"tag":"core","en":"take a taxi","pin":"dǎ chē","char":"打车"},
  {"id":141,"tag":"core","en":"watch / look","pin":"kàn","char":"看"},
  {"id":142,"tag":"family","en":"grandpa (dad's side)","pin":"yé yé","char":"爷爷"},
  {"id":143,"tag":"family","en":"grandma (dad's side)","pin":"nǎi nai","char":"奶奶"},
  {"id":144,"tag":"family","en":"grandpa (mum's side)","pin":"lǎo yé","char":"老爷"},
  {"id":145,"tag":"family","en":"grandma (mum's side)","pin":"lǎo lao","char":"姥姥"},
  {"id":146,"tag":"core","en":"big / small","pin":"dà / xiǎo","char":"大 / 小"},
  {"id":147,"tag":"core","en":"a bit","pin":"yì diǎn","char":"一点"},
  {"id":148,"tag":"phrases","en":"let me think","pin":"ràng wǒ xiǎng xiang","char":"让我想想"},
  {"id":149,"tag":"phrases","en":"please speak more slowly","pin":"màn yì diǎn","char":"慢一点"},
  {"id":150,"tag":"phrases","en":"very pleased to meet you","pin":"hěn gāo xìng rèn shì nǐ","char":"很高兴认识你"},
  {"id":151,"tag":"core","en":"can / be able to","pin":"néng","char":"能"},
  {"id":152,"tag":"core","en":"all / everybody","pin":"dōu","char":"都"},
  {"id":153,"tag":"sentences","en":"today it's very cold","pin":"jīn tiān hěn lěng","char":"今天很冷"},
  {"id":154,"tag":"sentences","en":"too hot","pin":"tài rè le","char":"太热了"},
  {"id":155,"tag":"sentences","en":"every student","pin":"měi ge xué shēng","char":"每个学生"},
  {"id":156,"tag":"core","en":"every day","pin":"měi tiān","char":"每天"},
  {"id":157,"tag":"objects","en":"paper","pin":"zhǐ","char":"纸"},
  {"id":158,"tag":"sentences","en":"Can you give me a piece of paper?","pin":"nǐ kě yǐ gěi wǒ yì zhāng zhǐ ma？","char":"你可以给我一张纸吗？"},
  {"id":159,"tag":"sentences","en":"Please give me a glass of water","pin":"qǐng gěi wǒ yì bēi shuǐ","char":"请给我一杯水"},
  {"id":160,"tag":"core","en":"need","pin":"xū yào","char":"需要"},
  {"id":161,"tag":"sentences","en":"I am in front of you","pin":"wǒ zài nǐ qián miàn","char":"我在你前面"},
  {"id":162,"tag":"clothing","en":"shoes","pin":"xié","char":"鞋"},
  {"id":163,"tag":"music","en":"pop music","pin":"liú xíng yīn yuè","char":"流行音乐"},
  {"id":164,"tag":"food","en":"buy groceries","pin":"mǎi cài","char":"买菜"},
  {"id":165,"tag":"core","en":"brand","pin":"pái zi","char":"牌子"},
  {"id":166,"tag":"food","en":"iced tea","pin":"bīng chá","char":"冰茶"},
  {"id":167,"tag":"sentences","en":"Please give me a cup of cold water","pin":"qǐng gěi wǒ yī bēi liáng shuǐ","char":"请给我一杯凉水"},
  {"id":168,"tag":"sentences","en":"I took a taxi home","pin":"wǒ zuò chū zū chē huí jiā","char":"我坐出租车回家"},
  {"id":169,"tag":"sentences","en":"everyone goes to China","pin":"dà jiā dōu qù zhōng guó","char":"大家都去中国"},
  {"id":170,"tag":"sentences","en":"every day","pin":"měi tiān","char":"每天"},
  {"id":171,"tag":"sentences","en":"I am wearing a piece of clothing","pin":"wǒ chuān le yí jiàn yī fu","char":"我穿了一件衣服"},
  {"id":172,"tag":"sentences","en":"I can cook because I'm not working tomorrow","pin":"wǒ néng zuò fàn yīn wèi míng tiān wǒ bù qù gōng zuò","char":"我能做饭因为明天我不去工作"},
  {"id":173,"tag":"sentences","en":"large / medium / small cup","pin":"dà bēi / zhōng bēi / xiǎo bēi","char":"大杯 / 中杯 / 小杯"},
  {"id":174,"tag":"sentences","en":"What size do you want?","pin":"nǐ xiǎng yào shén me dà xiǎo de？","char":"你想要什么大小的？"},
  {"id":175,"tag":"phrases","en":"at a friend's house","pin":"zài péng yǒu de jiā","char":"在朋友的家"},
  {"id":176,"tag":"slang","en":"really? / for real? (lit. real or fake?)","pin":"zhēn de jiǎ de？","char":"真的假的？"},
  {"id":177,"tag":"slang","en":"for real? (short form)","pin":"zhēn jiǎ？","char":"真假？"},
  {"id":178,"tag":"sentences","en":"What are you doing right now? (emphatic)","pin":"nǐ zhèng zài zuò shén me？","char":"你正在做什么？"},
  {"id":179,"tag":"core","en":"-ing (right now) — progressive marker","pin":"zhèng zài","char":"正在"},
  {"id":180,"tag":"sentences","en":"I am studying Chinese (right now)","pin":"wǒ zhèng zài xué xí zhōng wén","char":"我正在学习中文"},
  {"id":181,"tag":"core","en":"Chinese person / Chinese people","pin":"zhōng guó rén","char":"中国人"},
  {"id":182,"tag":"slang","en":"what (colloquial = 什么)","pin":"shá","char":"啥"},
  {"id":183,"tag":"slang","en":"do (colloquial = 做)","pin":"gàn","char":"干"},
  {"id":184,"tag":"slang","en":"whatcha doing? (colloquial)","pin":"gàn shá ne？","char":"干啥呢？"},
  {"id":185,"tag":"sentences","en":"I have already eaten breakfast","pin":"wǒ yǐ jīng chī le zǎo fàn le","char":"我已经吃了早饭了"},
  {"id":186,"tag":"sentences","en":"I have already eaten breakfast (alt)","pin":"wǒ yǐ jīng chī zǎo fàn le","char":"我已经吃早饭了"},
  {"id":187,"tag":"places","en":"restaurant (3 synonyms)","pin":"fàn diàn / fàn guǎn / cān tīng","char":"饭店 / 饭馆 / 餐厅"},
  {"id":188,"tag":"sentences","en":"I'm going to the restaurant with my friend","pin":"wǒ hé wǒ de péng yǒu yì qǐ qù fàn guǎn","char":"我和我的朋友一起去饭馆"},
  {"id":189,"tag":"sentences","en":"When are you (plural) going?","pin":"nǐ men shén me shí hou qù？","char":"你们什么时候去？"},
  {"id":190,"tag":"sentences","en":"We're going to the restaurant at 6pm","pin":"wǒ men xià wǔ liù diǎn qù fàn guǎn","char":"我们下午六点去饭馆"},
  {"id":191,"tag":"phrases","en":"do (it) once more","pin":"zài zuò yí cì","char":"再做一次"},
  {"id":192,"tag":"phrases","en":"eat one more","pin":"zài chī yí ge","char":"再吃一个"},
  {"id":193,"tag":"phrases","en":"have another cup of coffee","pin":"zài hē yì bēi kā fēi","char":"再喝一杯咖啡"},
  {"id":194,"tag":"phrases","en":"one more time (lit. come once again)","pin":"zài lái yí cì","char":"再来一次"},
  {"id":195,"tag":"phrases","en":"sorry — it's nothing / no worries","pin":"duì bù qǐ — méi shì","char":"对不起 — 没事"},
  {"id":196,"tag":"numbers","en":"nine","pin":"jiǔ","char":"九"},
  {"id":197,"tag":"core","en":"long time","pin":"jiǔ","char":"久"},
  {"id":198,"tag":"sentences","en":"if you're hungry, just eat","pin":"nǐ è le jiù chī","char":"你饿了就吃"},
  {"id":199,"tag":"sentences","en":"if you want it, buy it (corrected: jiù not jiǔ)","pin":"nǐ yào jiù mǎi","char":"你要就买"},
  {"id":200,"tag":"sentences","en":"I'm going to the shop to buy apples and Chinese food","pin":"wǒ qù shāng diàn mǎi píng guǒ hé zhōng guó cài","char":"我去商店买苹果和中国菜"},
  {"id":201,"tag":"sentences","en":"Who are you going with?","pin":"nǐ hé shéi yì qǐ qù？","char":"你和谁一起去？"},
  {"id":202,"tag":"sentences","en":"I go to a Chinese restaurant because I like Chinese food","pin":"wǒ qù zhōng fàn guǎn，yīn wèi wǒ xǐ huān chī zhōng guó cài","char":"我去中饭馆，因为我喜欢吃中国菜"},
  {"id":203,"tag":"food","en":"spicy hotpot","pin":"là de huǒ guō","char":"辣的火锅"},
  {"id":204,"tag":"core","en":"then / so / that","pin":"nà","char":"那"}
]
